// SimpleCacheOpenEntryResult.java is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     services/network/public/mojom/network_service_test.mojom
//

package org.chromium.network.mojom;

public final class SimpleCacheOpenEntryResult extends org.chromium.mojo.bindings.Struct {

  private static final int STRUCT_SIZE = 32;
  private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY =
      new org.chromium.mojo.bindings.DataHeader[] {
        new org.chromium.mojo.bindings.DataHeader(32, 0)
      };
  private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
  public int error;
  public String key;
  public SimpleCacheEntry entry;

  private SimpleCacheOpenEntryResult(int version) {
    super(STRUCT_SIZE, version);
  }

  public SimpleCacheOpenEntryResult() {
    this(0);
  }

  public static SimpleCacheOpenEntryResult deserialize(org.chromium.mojo.bindings.Message message) {
    return decode(new org.chromium.mojo.bindings.Decoder(message));
  }

  /**
   * Similar to the method above, but deserializes from a |ByteBuffer| instance.
   *
   * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
   */
  public static SimpleCacheOpenEntryResult deserialize(java.nio.ByteBuffer data) {
    return deserialize(
        new org.chromium.mojo.bindings.Message(
            data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
  }

  @SuppressWarnings("unchecked")
  public static SimpleCacheOpenEntryResult decode(org.chromium.mojo.bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    decoder0.increaseStackDepth();
    SimpleCacheOpenEntryResult result;
    try {
      org.chromium.mojo.bindings.DataHeader mainDataHeader =
          decoder0.readAndValidateDataHeader(VERSION_ARRAY);
      final int elementsOrVersion = mainDataHeader.elementsOrVersion;
      result = new SimpleCacheOpenEntryResult(elementsOrVersion);
      {
        result.error = decoder0.readInt(8);
      }
      {
        result.key = decoder0.readString(16, false);
      }
      {
        result.entry = decoder0.readServiceInterface(24, true, SimpleCacheEntry.MANAGER);
      }

    } finally {
      decoder0.decreaseStackDepth();
    }
    return result;
  }

  @SuppressWarnings("unchecked")
  @Override
  public final void encode(org.chromium.mojo.bindings.Encoder encoder) {
    org.chromium.mojo.bindings.Encoder encoder0 =
        encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);

    encoder0.encode(this.error, 8);

    encoder0.encode(this.key, 16, false);

    encoder0.encode(this.entry, 24, true, SimpleCacheEntry.MANAGER);
  }
}
