// FilterConfig.java is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     components/attribution_reporting/registration.mojom
//

package org.chromium.attribution_reporting.mojom;

public final class FilterConfig extends org.chromium.mojo.bindings.Struct {

  private static final int STRUCT_SIZE = 24;
  private static final org.chromium.mojo.bindings.DataHeader[] VERSION_ARRAY =
      new org.chromium.mojo.bindings.DataHeader[] {
        new org.chromium.mojo.bindings.DataHeader(24, 0)
      };
  private static final org.chromium.mojo.bindings.DataHeader DEFAULT_STRUCT_INFO = VERSION_ARRAY[0];
  public org.chromium.mojo_base.mojom.TimeDelta lookbackWindow;
  public java.util.Map<String, String[]> filterValues;

  private FilterConfig(int version) {
    super(STRUCT_SIZE, version);
  }

  public FilterConfig() {
    this(0);
  }

  public static FilterConfig deserialize(org.chromium.mojo.bindings.Message message) {
    return decode(new org.chromium.mojo.bindings.Decoder(message));
  }

  /**
   * Similar to the method above, but deserializes from a |ByteBuffer| instance.
   *
   * @throws org.chromium.mojo.bindings.DeserializationException on deserialization failure.
   */
  public static FilterConfig deserialize(java.nio.ByteBuffer data) {
    return deserialize(
        new org.chromium.mojo.bindings.Message(
            data, new java.util.ArrayList<org.chromium.mojo.system.Handle>()));
  }

  @SuppressWarnings("unchecked")
  public static FilterConfig decode(org.chromium.mojo.bindings.Decoder decoder0) {
    if (decoder0 == null) {
      return null;
    }
    decoder0.increaseStackDepth();
    FilterConfig result;
    try {
      org.chromium.mojo.bindings.DataHeader mainDataHeader =
          decoder0.readAndValidateDataHeader(VERSION_ARRAY);
      final int elementsOrVersion = mainDataHeader.elementsOrVersion;
      result = new FilterConfig(elementsOrVersion);
      {
        org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(8, true);
        result.lookbackWindow = org.chromium.mojo_base.mojom.TimeDelta.decode(decoder1);
      }
      {
        org.chromium.mojo.bindings.Decoder decoder1 = decoder0.readPointer(16, false);
        {
          decoder1.readDataHeaderForMap();
          String[] keys0;
          String[][] values0;
          {
            org.chromium.mojo.bindings.Decoder decoder2 =
                decoder1.readPointer(org.chromium.mojo.bindings.DataHeader.HEADER_SIZE, false);
            {
              org.chromium.mojo.bindings.DataHeader si2 =
                  decoder2.readDataHeaderForPointerArray(
                      org.chromium.mojo.bindings.BindingsHelper.UNSPECIFIED_ARRAY_LENGTH);
              keys0 = new String[si2.elementsOrVersion];
              for (int i2 = 0; i2 < si2.elementsOrVersion; ++i2) {

                keys0[i2] =
                    decoder2.readString(
                        org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                            + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE * i2,
                        false);
              }
            }
          }
          {
            org.chromium.mojo.bindings.Decoder decoder2 =
                decoder1.readPointer(
                    org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                        + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE,
                    false);
            {
              org.chromium.mojo.bindings.DataHeader si2 =
                  decoder2.readDataHeaderForPointerArray(keys0.length);
              values0 = new String[si2.elementsOrVersion][];
              for (int i2 = 0; i2 < si2.elementsOrVersion; ++i2) {

                org.chromium.mojo.bindings.Decoder decoder3 =
                    decoder2.readPointer(
                        org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                            + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE * i2,
                        false);
                {
                  org.chromium.mojo.bindings.DataHeader si3 =
                      decoder3.readDataHeaderForPointerArray(
                          org.chromium.mojo.bindings.BindingsHelper.UNSPECIFIED_ARRAY_LENGTH);
                  values0[i2] = new String[si3.elementsOrVersion];
                  for (int i3 = 0; i3 < si3.elementsOrVersion; ++i3) {

                    values0[i2][i3] =
                        decoder3.readString(
                            org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                                + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE * i3,
                            false);
                  }
                }
              }
            }
          }
          result.filterValues = new java.util.HashMap<String, String[]>();
          for (int index0 = 0; index0 < keys0.length; ++index0) {
            result.filterValues.put(keys0[index0], values0[index0]);
          }
        }
      }

    } finally {
      decoder0.decreaseStackDepth();
    }
    return result;
  }

  @SuppressWarnings("unchecked")
  @Override
  public final void encode(org.chromium.mojo.bindings.Encoder encoder) {
    org.chromium.mojo.bindings.Encoder encoder0 =
        encoder.getEncoderAtDataOffset(DEFAULT_STRUCT_INFO);

    encoder0.encode(this.lookbackWindow, 8, true);

    if (this.filterValues == null) {
      encoder0.encodeNullPointer(16, false);
    } else {
      org.chromium.mojo.bindings.Encoder encoder1 = encoder0.encoderForMap(16);
      int size0 = this.filterValues.size();
      String[] keys0 = new String[size0];
      String[][] values0 = new String[size0][];
      int index0 = 0;
      for (java.util.Map.Entry<String, String[]> entry0 : this.filterValues.entrySet()) {
        keys0[index0] = entry0.getKey();
        values0[index0] = entry0.getValue();
        ++index0;
      }

      {
        org.chromium.mojo.bindings.Encoder encoder2 =
            encoder1.encodePointerArray(
                keys0.length,
                org.chromium.mojo.bindings.DataHeader.HEADER_SIZE,
                org.chromium.mojo.bindings.BindingsHelper.UNSPECIFIED_ARRAY_LENGTH);
        for (int i1 = 0; i1 < keys0.length; ++i1) {

          encoder2.encode(
              keys0[i1],
              org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                  + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE * i1,
              false);
        }
      }

      {
        org.chromium.mojo.bindings.Encoder encoder2 =
            encoder1.encodePointerArray(
                values0.length,
                org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                    + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE,
                org.chromium.mojo.bindings.BindingsHelper.UNSPECIFIED_ARRAY_LENGTH);
        for (int i1 = 0; i1 < values0.length; ++i1) {

          if (values0[i1] == null) {
            encoder2.encodeNullPointer(
                org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                    + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE * i1,
                false);
          } else {
            org.chromium.mojo.bindings.Encoder encoder3 =
                encoder2.encodePointerArray(
                    values0[i1].length,
                    org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                        + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE * i1,
                    org.chromium.mojo.bindings.BindingsHelper.UNSPECIFIED_ARRAY_LENGTH);
            for (int i2 = 0; i2 < values0[i1].length; ++i2) {

              encoder3.encode(
                  values0[i1][i2],
                  org.chromium.mojo.bindings.DataHeader.HEADER_SIZE
                      + org.chromium.mojo.bindings.BindingsHelper.POINTER_SIZE * i2,
                  false);
            }
          }
        }
      }
    }
  }
}
