// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: variations_seed.proto

package org.chromium.components.variations;

public final class VariationsSeedOuterClass {
  private VariationsSeedOuterClass() {}

  public static void registerAllExtensions(com.google.protobuf.ExtensionRegistryLite registry) {}

  public interface VariationsSeedOrBuilder
      extends
      // @@protoc_insertion_point(interface_extends:variations.VariationsSeed)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @return Whether the serialNumber field is set.
     */
    boolean hasSerialNumber();

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @return The serialNumber.
     */
    java.lang.String getSerialNumber();

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @return The bytes for serialNumber.
     */
    com.google.protobuf.ByteString getSerialNumberBytes();

    /** <code>repeated .variations.Study study = 2;</code> */
    java.util.List<org.chromium.components.variations.StudyOuterClass.Study> getStudyList();

    /** <code>repeated .variations.Study study = 2;</code> */
    org.chromium.components.variations.StudyOuterClass.Study getStudy(int index);

    /** <code>repeated .variations.Study study = 2;</code> */
    int getStudyCount();

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @return Whether the countryCode field is set.
     */
    @java.lang.Deprecated
    boolean hasCountryCode();

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @return The countryCode.
     */
    @java.lang.Deprecated
    java.lang.String getCountryCode();

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @return The bytes for countryCode.
     */
    @java.lang.Deprecated
    com.google.protobuf.ByteString getCountryCodeBytes();

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @return Whether the version field is set.
     */
    boolean hasVersion();

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @return The version.
     */
    java.lang.String getVersion();

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @return The bytes for version.
     */
    com.google.protobuf.ByteString getVersionBytes();

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    java.util.List<org.chromium.components.variations.LayerOuterClass.Layer> getLayersList();

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    org.chromium.components.variations.LayerOuterClass.Layer getLayers(int index);

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    int getLayersCount();
  }

  /**
   *
   *
   * <pre>
   * The VariationsSeed is a protobuf response from the server that contains the
   * list of studies and a serial number to uniquely identify its contents. The
   * serial number allows the client to easily determine if the list of
   * experiments has changed from the previous VariationsSeed seen by the client.
   * Next tag: 7
   * </pre>
   *
   * Protobuf type {@code variations.VariationsSeed}
   */
  public static final class VariationsSeed
      extends com.google.protobuf.GeneratedMessageLite<VariationsSeed, VariationsSeed.Builder>
      implements
      // @@protoc_insertion_point(message_implements:variations.VariationsSeed)
      VariationsSeedOrBuilder {
    private VariationsSeed() {
      serialNumber_ = "";
      study_ = emptyProtobufList();
      countryCode_ = "";
      version_ = "";
      layers_ = emptyProtobufList();
    }

    private int bitField0_;
    public static final int SERIAL_NUMBER_FIELD_NUMBER = 1;
    private java.lang.String serialNumber_;

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @return Whether the serialNumber field is set.
     */
    @java.lang.Override
    public boolean hasSerialNumber() {
      return ((bitField0_ & 0x00000001) != 0);
    }

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @return The serialNumber.
     */
    @java.lang.Override
    public java.lang.String getSerialNumber() {
      return serialNumber_;
    }

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @return The bytes for serialNumber.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getSerialNumberBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(serialNumber_);
    }

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @param value The serialNumber to set.
     */
    private void setSerialNumber(java.lang.String value) {
      value.getClass();
      bitField0_ |= 0x00000001;
      serialNumber_ = value;
    }

    /** <code>optional string serial_number = 1;</code> */
    private void clearSerialNumber() {
      bitField0_ = (bitField0_ & ~0x00000001);
      serialNumber_ = getDefaultInstance().getSerialNumber();
    }

    /**
     * <code>optional string serial_number = 1;</code>
     *
     * @param value The bytes for serialNumber to set.
     */
    private void setSerialNumberBytes(com.google.protobuf.ByteString value) {
      serialNumber_ = value.toStringUtf8();
      bitField0_ |= 0x00000001;
    }

    public static final int STUDY_FIELD_NUMBER = 2;
    private com.google.protobuf.Internal.ProtobufList<
            org.chromium.components.variations.StudyOuterClass.Study>
        study_;

    /** <code>repeated .variations.Study study = 2;</code> */
    @java.lang.Override
    public java.util.List<org.chromium.components.variations.StudyOuterClass.Study> getStudyList() {
      return study_;
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    public java.util.List<
            ? extends org.chromium.components.variations.StudyOuterClass.StudyOrBuilder>
        getStudyOrBuilderList() {
      return study_;
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    @java.lang.Override
    public int getStudyCount() {
      return study_.size();
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    @java.lang.Override
    public org.chromium.components.variations.StudyOuterClass.Study getStudy(int index) {
      return study_.get(index);
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    public org.chromium.components.variations.StudyOuterClass.StudyOrBuilder getStudyOrBuilder(
        int index) {
      return study_.get(index);
    }

    private void ensureStudyIsMutable() {
      com.google.protobuf.Internal.ProtobufList<
              org.chromium.components.variations.StudyOuterClass.Study>
          tmp = study_;
      if (!tmp.isModifiable()) {
        study_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
      }
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    private void setStudy(
        int index, org.chromium.components.variations.StudyOuterClass.Study value) {
      value.getClass();
      ensureStudyIsMutable();
      study_.set(index, value);
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    private void addStudy(org.chromium.components.variations.StudyOuterClass.Study value) {
      value.getClass();
      ensureStudyIsMutable();
      study_.add(value);
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    private void addStudy(
        int index, org.chromium.components.variations.StudyOuterClass.Study value) {
      value.getClass();
      ensureStudyIsMutable();
      study_.add(index, value);
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    private void addAllStudy(
        java.lang.Iterable<? extends org.chromium.components.variations.StudyOuterClass.Study>
            values) {
      ensureStudyIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(values, study_);
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    private void clearStudy() {
      study_ = emptyProtobufList();
    }

    /** <code>repeated .variations.Study study = 2;</code> */
    private void removeStudy(int index) {
      ensureStudyIsMutable();
      study_.remove(index);
    }

    public static final int COUNTRY_CODE_FIELD_NUMBER = 3;
    private java.lang.String countryCode_;

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @return Whether the countryCode field is set.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public boolean hasCountryCode() {
      return ((bitField0_ & 0x00000002) != 0);
    }

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @return The countryCode.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public java.lang.String getCountryCode() {
      return countryCode_;
    }

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @return The bytes for countryCode.
     */
    @java.lang.Override
    @java.lang.Deprecated
    public com.google.protobuf.ByteString getCountryCodeBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(countryCode_);
    }

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @param value The countryCode to set.
     */
    private void setCountryCode(java.lang.String value) {
      value.getClass();
      bitField0_ |= 0x00000002;
      countryCode_ = value;
    }

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     */
    private void clearCountryCode() {
      bitField0_ = (bitField0_ & ~0x00000002);
      countryCode_ = getDefaultInstance().getCountryCode();
    }

    /**
     *
     *
     * <pre>
     * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
     * address. Deprecated.
     * </pre>
     *
     * <code>optional string country_code = 3 [deprecated = true];</code>
     *
     * @param value The bytes for countryCode to set.
     */
    private void setCountryCodeBytes(com.google.protobuf.ByteString value) {
      countryCode_ = value.toStringUtf8();
      bitField0_ |= 0x00000002;
    }

    public static final int VERSION_FIELD_NUMBER = 4;
    private java.lang.String version_;

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @return Whether the version field is set.
     */
    @java.lang.Override
    public boolean hasVersion() {
      return ((bitField0_ & 0x00000004) != 0);
    }

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @return The version.
     */
    @java.lang.Override
    public java.lang.String getVersion() {
      return version_;
    }

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @return The bytes for version.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString getVersionBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(version_);
    }

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @param value The version to set.
     */
    private void setVersion(java.lang.String value) {
      value.getClass();
      bitField0_ |= 0x00000004;
      version_ = value;
    }

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     */
    private void clearVersion() {
      bitField0_ = (bitField0_ & ~0x00000004);
      version_ = getDefaultInstance().getVersion();
    }

    /**
     *
     *
     * <pre>
     * A version string which identifies the version of the configuration files
     * that this seed was generated from.
     * </pre>
     *
     * <code>optional string version = 4;</code>
     *
     * @param value The bytes for version to set.
     */
    private void setVersionBytes(com.google.protobuf.ByteString value) {
      version_ = value.toStringUtf8();
      bitField0_ |= 0x00000004;
    }

    public static final int LAYERS_FIELD_NUMBER = 6;
    private com.google.protobuf.Internal.ProtobufList<
            org.chromium.components.variations.LayerOuterClass.Layer>
        layers_;

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    @java.lang.Override
    public java.util.List<org.chromium.components.variations.LayerOuterClass.Layer>
        getLayersList() {
      return layers_;
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    public java.util.List<
            ? extends org.chromium.components.variations.LayerOuterClass.LayerOrBuilder>
        getLayersOrBuilderList() {
      return layers_;
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    @java.lang.Override
    public int getLayersCount() {
      return layers_.size();
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    @java.lang.Override
    public org.chromium.components.variations.LayerOuterClass.Layer getLayers(int index) {
      return layers_.get(index);
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    public org.chromium.components.variations.LayerOuterClass.LayerOrBuilder getLayersOrBuilder(
        int index) {
      return layers_.get(index);
    }

    private void ensureLayersIsMutable() {
      com.google.protobuf.Internal.ProtobufList<
              org.chromium.components.variations.LayerOuterClass.Layer>
          tmp = layers_;
      if (!tmp.isModifiable()) {
        layers_ = com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
      }
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    private void setLayers(
        int index, org.chromium.components.variations.LayerOuterClass.Layer value) {
      value.getClass();
      ensureLayersIsMutable();
      layers_.set(index, value);
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    private void addLayers(org.chromium.components.variations.LayerOuterClass.Layer value) {
      value.getClass();
      ensureLayersIsMutable();
      layers_.add(value);
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    private void addLayers(
        int index, org.chromium.components.variations.LayerOuterClass.Layer value) {
      value.getClass();
      ensureLayersIsMutable();
      layers_.add(index, value);
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    private void addAllLayers(
        java.lang.Iterable<? extends org.chromium.components.variations.LayerOuterClass.Layer>
            values) {
      ensureLayersIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(values, layers_);
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    private void clearLayers() {
      layers_ = emptyProtobufList();
    }

    /**
     *
     *
     * <pre>
     * A list of layers where each study can optionally be part of one, with
     * clients ensuring that only one study per layer is enabled.
     * </pre>
     *
     * <code>repeated .variations.Layer layers = 6;</code>
     */
    private void removeLayers(int index) {
      ensureLayersIsMutable();
      layers_.remove(index);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(
            java.nio.ByteBuffer data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(byte[] data) throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, data);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(byte[] data, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(java.io.InputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseDelimitedFrom(java.io.InputStream input) throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseDelimitedFrom(
            java.io.InputStream input, com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(com.google.protobuf.CodedInputStream input) throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(DEFAULT_INSTANCE, input);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }

    public static Builder newBuilder(
        org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     *
     *
     * <pre>
     * The VariationsSeed is a protobuf response from the server that contains the
     * list of studies and a serial number to uniquely identify its contents. The
     * serial number allows the client to easily determine if the list of
     * experiments has changed from the previous VariationsSeed seen by the client.
     * Next tag: 7
     * </pre>
     *
     * Protobuf type {@code variations.VariationsSeed}
     */
    public static final class Builder
        extends com.google.protobuf.GeneratedMessageLite.Builder<
            org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed, Builder>
        implements
        // @@protoc_insertion_point(builder_implements:variations.VariationsSeed)
        org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeedOrBuilder {
      // Construct using
      private Builder() {
        super(DEFAULT_INSTANCE);
      }

      /**
       * <code>optional string serial_number = 1;</code>
       *
       * @return Whether the serialNumber field is set.
       */
      @java.lang.Override
      public boolean hasSerialNumber() {
        return instance.hasSerialNumber();
      }

      /**
       * <code>optional string serial_number = 1;</code>
       *
       * @return The serialNumber.
       */
      @java.lang.Override
      public java.lang.String getSerialNumber() {
        return instance.getSerialNumber();
      }

      /**
       * <code>optional string serial_number = 1;</code>
       *
       * @return The bytes for serialNumber.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getSerialNumberBytes() {
        return instance.getSerialNumberBytes();
      }

      /**
       * <code>optional string serial_number = 1;</code>
       *
       * @param value The serialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSerialNumber(java.lang.String value) {
        copyOnWrite();
        instance.setSerialNumber(value);
        return this;
      }

      /**
       * <code>optional string serial_number = 1;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearSerialNumber() {
        copyOnWrite();
        instance.clearSerialNumber();
        return this;
      }

      /**
       * <code>optional string serial_number = 1;</code>
       *
       * @param value The bytes for serialNumber to set.
       * @return This builder for chaining.
       */
      public Builder setSerialNumberBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setSerialNumberBytes(value);
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      @java.lang.Override
      public java.util.List<org.chromium.components.variations.StudyOuterClass.Study>
          getStudyList() {
        return java.util.Collections.unmodifiableList(instance.getStudyList());
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      @java.lang.Override
      public int getStudyCount() {
        return instance.getStudyCount();
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      @java.lang.Override
      public org.chromium.components.variations.StudyOuterClass.Study getStudy(int index) {
        return instance.getStudy(index);
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder setStudy(
          int index, org.chromium.components.variations.StudyOuterClass.Study value) {
        copyOnWrite();
        instance.setStudy(index, value);
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder setStudy(
          int index,
          org.chromium.components.variations.StudyOuterClass.Study.Builder builderForValue) {
        copyOnWrite();
        instance.setStudy(index, builderForValue.build());
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder addStudy(org.chromium.components.variations.StudyOuterClass.Study value) {
        copyOnWrite();
        instance.addStudy(value);
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder addStudy(
          int index, org.chromium.components.variations.StudyOuterClass.Study value) {
        copyOnWrite();
        instance.addStudy(index, value);
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder addStudy(
          org.chromium.components.variations.StudyOuterClass.Study.Builder builderForValue) {
        copyOnWrite();
        instance.addStudy(builderForValue.build());
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder addStudy(
          int index,
          org.chromium.components.variations.StudyOuterClass.Study.Builder builderForValue) {
        copyOnWrite();
        instance.addStudy(index, builderForValue.build());
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder addAllStudy(
          java.lang.Iterable<? extends org.chromium.components.variations.StudyOuterClass.Study>
              values) {
        copyOnWrite();
        instance.addAllStudy(values);
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder clearStudy() {
        copyOnWrite();
        instance.clearStudy();
        return this;
      }

      /** <code>repeated .variations.Study study = 2;</code> */
      public Builder removeStudy(int index) {
        copyOnWrite();
        instance.removeStudy(index);
        return this;
      }

      /**
       *
       *
       * <pre>
       * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
       * address. Deprecated.
       * </pre>
       *
       * <code>optional string country_code = 3 [deprecated = true];</code>
       *
       * @return Whether the countryCode field is set.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public boolean hasCountryCode() {
        return instance.hasCountryCode();
      }

      /**
       *
       *
       * <pre>
       * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
       * address. Deprecated.
       * </pre>
       *
       * <code>optional string country_code = 3 [deprecated = true];</code>
       *
       * @return The countryCode.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public java.lang.String getCountryCode() {
        return instance.getCountryCode();
      }

      /**
       *
       *
       * <pre>
       * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
       * address. Deprecated.
       * </pre>
       *
       * <code>optional string country_code = 3 [deprecated = true];</code>
       *
       * @return The bytes for countryCode.
       */
      @java.lang.Override
      @java.lang.Deprecated
      public com.google.protobuf.ByteString getCountryCodeBytes() {
        return instance.getCountryCodeBytes();
      }

      /**
       *
       *
       * <pre>
       * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
       * address. Deprecated.
       * </pre>
       *
       * <code>optional string country_code = 3 [deprecated = true];</code>
       *
       * @param value The countryCode to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated
      public Builder setCountryCode(java.lang.String value) {
        copyOnWrite();
        instance.setCountryCode(value);
        return this;
      }

      /**
       *
       *
       * <pre>
       * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
       * address. Deprecated.
       * </pre>
       *
       * <code>optional string country_code = 3 [deprecated = true];</code>
       *
       * @return This builder for chaining.
       */
      @java.lang.Deprecated
      public Builder clearCountryCode() {
        copyOnWrite();
        instance.clearCountryCode();
        return this;
      }

      /**
       *
       *
       * <pre>
       * Lowercase ISO 3166-1 alpha-2 country code of the client, according to IP
       * address. Deprecated.
       * </pre>
       *
       * <code>optional string country_code = 3 [deprecated = true];</code>
       *
       * @param value The bytes for countryCode to set.
       * @return This builder for chaining.
       */
      @java.lang.Deprecated
      public Builder setCountryCodeBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCountryCodeBytes(value);
        return this;
      }

      /**
       *
       *
       * <pre>
       * A version string which identifies the version of the configuration files
       * that this seed was generated from.
       * </pre>
       *
       * <code>optional string version = 4;</code>
       *
       * @return Whether the version field is set.
       */
      @java.lang.Override
      public boolean hasVersion() {
        return instance.hasVersion();
      }

      /**
       *
       *
       * <pre>
       * A version string which identifies the version of the configuration files
       * that this seed was generated from.
       * </pre>
       *
       * <code>optional string version = 4;</code>
       *
       * @return The version.
       */
      @java.lang.Override
      public java.lang.String getVersion() {
        return instance.getVersion();
      }

      /**
       *
       *
       * <pre>
       * A version string which identifies the version of the configuration files
       * that this seed was generated from.
       * </pre>
       *
       * <code>optional string version = 4;</code>
       *
       * @return The bytes for version.
       */
      @java.lang.Override
      public com.google.protobuf.ByteString getVersionBytes() {
        return instance.getVersionBytes();
      }

      /**
       *
       *
       * <pre>
       * A version string which identifies the version of the configuration files
       * that this seed was generated from.
       * </pre>
       *
       * <code>optional string version = 4;</code>
       *
       * @param value The version to set.
       * @return This builder for chaining.
       */
      public Builder setVersion(java.lang.String value) {
        copyOnWrite();
        instance.setVersion(value);
        return this;
      }

      /**
       *
       *
       * <pre>
       * A version string which identifies the version of the configuration files
       * that this seed was generated from.
       * </pre>
       *
       * <code>optional string version = 4;</code>
       *
       * @return This builder for chaining.
       */
      public Builder clearVersion() {
        copyOnWrite();
        instance.clearVersion();
        return this;
      }

      /**
       *
       *
       * <pre>
       * A version string which identifies the version of the configuration files
       * that this seed was generated from.
       * </pre>
       *
       * <code>optional string version = 4;</code>
       *
       * @param value The bytes for version to set.
       * @return This builder for chaining.
       */
      public Builder setVersionBytes(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setVersionBytes(value);
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      @java.lang.Override
      public java.util.List<org.chromium.components.variations.LayerOuterClass.Layer>
          getLayersList() {
        return java.util.Collections.unmodifiableList(instance.getLayersList());
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      @java.lang.Override
      public int getLayersCount() {
        return instance.getLayersCount();
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      @java.lang.Override
      public org.chromium.components.variations.LayerOuterClass.Layer getLayers(int index) {
        return instance.getLayers(index);
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder setLayers(
          int index, org.chromium.components.variations.LayerOuterClass.Layer value) {
        copyOnWrite();
        instance.setLayers(index, value);
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder setLayers(
          int index,
          org.chromium.components.variations.LayerOuterClass.Layer.Builder builderForValue) {
        copyOnWrite();
        instance.setLayers(index, builderForValue.build());
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder addLayers(org.chromium.components.variations.LayerOuterClass.Layer value) {
        copyOnWrite();
        instance.addLayers(value);
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder addLayers(
          int index, org.chromium.components.variations.LayerOuterClass.Layer value) {
        copyOnWrite();
        instance.addLayers(index, value);
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder addLayers(
          org.chromium.components.variations.LayerOuterClass.Layer.Builder builderForValue) {
        copyOnWrite();
        instance.addLayers(builderForValue.build());
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder addLayers(
          int index,
          org.chromium.components.variations.LayerOuterClass.Layer.Builder builderForValue) {
        copyOnWrite();
        instance.addLayers(index, builderForValue.build());
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder addAllLayers(
          java.lang.Iterable<? extends org.chromium.components.variations.LayerOuterClass.Layer>
              values) {
        copyOnWrite();
        instance.addAllLayers(values);
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder clearLayers() {
        copyOnWrite();
        instance.clearLayers();
        return this;
      }

      /**
       *
       *
       * <pre>
       * A list of layers where each study can optionally be part of one, with
       * clients ensuring that only one study per layer is enabled.
       * </pre>
       *
       * <code>repeated .variations.Layer layers = 6;</code>
       */
      public Builder removeLayers(int index) {
        copyOnWrite();
        instance.removeLayers(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:variations.VariationsSeed)
    }

    private byte memoizedIsInitialized = 2;

    @java.lang.Override
    @java.lang.SuppressWarnings({"unchecked", "fallthrough"})
    protected final java.lang.Object dynamicMethod(
        com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
        java.lang.Object arg0,
        java.lang.Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE:
          {
            return new org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed();
          }
        case NEW_BUILDER:
          {
            return new Builder();
          }
        case BUILD_MESSAGE_INFO:
          {
            java.lang.Object[] objects =
                new java.lang.Object[] {
                  "bitField0_",
                  "serialNumber_",
                  "study_",
                  org.chromium.components.variations.StudyOuterClass.Study.class,
                  "countryCode_",
                  "version_",
                  "layers_",
                  org.chromium.components.variations.LayerOuterClass.Layer.class,
                };
            java.lang.String info =
                "\u0001\u0005\u0000\u0001\u0001\u0006\u0005\u0000\u0002\u0001\u0001\u1008\u0000\u0002"
                    + "\u041b\u0003\u1008\u0001\u0004\u1008\u0002\u0006\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
          }
          // fall through
        case GET_DEFAULT_INSTANCE:
          {
            return DEFAULT_INSTANCE;
          }
        case GET_PARSER:
          {
            com.google.protobuf.Parser<
                    org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed>
                parser = PARSER;
            if (parser == null) {
              synchronized (
                  org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
                      .class) {
                parser = PARSER;
                if (parser == null) {
                  parser =
                      new DefaultInstanceBasedParser<
                          org.chromium.components.variations.VariationsSeedOuterClass
                              .VariationsSeed>(DEFAULT_INSTANCE);
                  PARSER = parser;
                }
              }
            }
            return parser;
          }
        case GET_MEMOIZED_IS_INITIALIZED:
          {
            return memoizedIsInitialized;
          }
        case SET_MEMOIZED_IS_INITIALIZED:
          {
            memoizedIsInitialized = (byte) (arg0 == null ? 0 : 1);
            return null;
          }
      }
      throw new UnsupportedOperationException();
    }

    // @@protoc_insertion_point(class_scope:variations.VariationsSeed)
    private static final org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        DEFAULT_INSTANCE;

    static {
      VariationsSeed defaultInstance = new VariationsSeed();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
          VariationsSeed.class, defaultInstance);
    }

    public static org.chromium.components.variations.VariationsSeedOuterClass.VariationsSeed
        getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<VariationsSeed> PARSER;

    public static com.google.protobuf.Parser<VariationsSeed> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
