// Copyright 2024 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by
//     java_cpp_enum.py
// From
//     ../../media/base/android/media_codec_bridge.h

package org.chromium.media;

import androidx.annotation.IntDef;
import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

@IntDef({
  MediaCodecStatus.OK,
  MediaCodecStatus.TRY_AGAIN_LATER,
  MediaCodecStatus.OUTPUT_BUFFERS_CHANGED,
  MediaCodecStatus.OUTPUT_FORMAT_CHANGED,
  MediaCodecStatus.NO_KEY,
  MediaCodecStatus.ERROR,
  MediaCodecStatus.KEY_EXPIRED,
  MediaCodecStatus.RESOURCE_BUSY,
  MediaCodecStatus.INSUFFICIENT_OUTPUT_PROTECTION,
  MediaCodecStatus.SESSION_NOT_OPENED,
  MediaCodecStatus.UNSUPPORTED_OPERATION,
  MediaCodecStatus.INSUFFICIENT_SECURITY,
  MediaCodecStatus.FRAME_TOO_LARGE,
  MediaCodecStatus.LOST_STATE,
  MediaCodecStatus.GENERIC_OEM,
  MediaCodecStatus.GENERIC_PLUGIN,
  MediaCodecStatus.LICENSE_PARSE,
  MediaCodecStatus.MEDIA_FRAMEWORK,
  MediaCodecStatus.ZERO_SUBSAMPLES,
  MediaCodecStatus.UNKNOWN_CIPHER_MODE,
  MediaCodecStatus.PATTERN_ENCRYPTION_NOT_SUPPORTED
})
@Retention(RetentionPolicy.SOURCE)
public @interface MediaCodecStatus {
  int OK = 0;
  int TRY_AGAIN_LATER = 1;
  int OUTPUT_BUFFERS_CHANGED = 2;
  int OUTPUT_FORMAT_CHANGED = 3;
  int NO_KEY = 4;
  int ERROR = 5;
  int KEY_EXPIRED = 6;
  int RESOURCE_BUSY = 7;
  int INSUFFICIENT_OUTPUT_PROTECTION = 8;
  int SESSION_NOT_OPENED = 9;
  int UNSUPPORTED_OPERATION = 10;
  int INSUFFICIENT_SECURITY = 11;
  int FRAME_TOO_LARGE = 12;
  int LOST_STATE = 13;
  int GENERIC_OEM = 14;
  int GENERIC_PLUGIN = 15;
  int LICENSE_PARSE = 16;
  int MEDIA_FRAMEWORK = 17;
  int ZERO_SUBSAMPLES = 18;
  int UNKNOWN_CIPHER_MODE = 19;
  int PATTERN_ENCRYPTION_NOT_SUPPORTED = 20;
}
