//
// This file was generated by third_party/jni_zero/jni_generator.py
//
package org.chromium.content.browser;

import org.jni_zero.CheckDiscard;
import org.jni_zero.GEN_JNI;
import org.jni_zero.JniStaticTestMocker;
import org.jni_zero.NativeLibraryLoadedStatus;

@CheckDiscard("crbug.com/993421")
class SpeechRecognitionImplJni implements SpeechRecognitionImpl.Natives {
  private static SpeechRecognitionImpl.Natives testInstance;

  public static final JniStaticTestMocker<SpeechRecognitionImpl.Natives> TEST_HOOKS =
      new JniStaticTestMocker<SpeechRecognitionImpl.Natives>() {
        @Override
        public void setInstanceForTesting(SpeechRecognitionImpl.Natives instance) {
          if (!GEN_JNI.TESTING_ENABLED) {
            throw new RuntimeException("Tried to set a JNI mock when mocks aren't enabled!");
          }
          testInstance = instance;
        }
      };

  @Override
  public void onAudioEnd(long nativeSpeechRecognizerImplAndroid, SpeechRecognitionImpl caller) {
    assert nativeSpeechRecognizerImplAndroid != 0;
    GEN_JNI.org_chromium_content_browser_SpeechRecognitionImpl_onAudioEnd(
        nativeSpeechRecognizerImplAndroid, caller);
  }

  @Override
  public void onAudioStart(long nativeSpeechRecognizerImplAndroid, SpeechRecognitionImpl caller) {
    assert nativeSpeechRecognizerImplAndroid != 0;
    GEN_JNI.org_chromium_content_browser_SpeechRecognitionImpl_onAudioStart(
        nativeSpeechRecognizerImplAndroid, caller);
  }

  @Override
  public void onRecognitionEnd(
      long nativeSpeechRecognizerImplAndroid, SpeechRecognitionImpl caller) {
    assert nativeSpeechRecognizerImplAndroid != 0;
    GEN_JNI.org_chromium_content_browser_SpeechRecognitionImpl_onRecognitionEnd(
        nativeSpeechRecognizerImplAndroid, caller);
  }

  @Override
  public void onRecognitionError(
      long nativeSpeechRecognizerImplAndroid, SpeechRecognitionImpl caller, int error) {
    assert nativeSpeechRecognizerImplAndroid != 0;
    GEN_JNI.org_chromium_content_browser_SpeechRecognitionImpl_onRecognitionError(
        nativeSpeechRecognizerImplAndroid, caller, error);
  }

  @Override
  public void onRecognitionResults(
      long nativeSpeechRecognizerImplAndroid,
      SpeechRecognitionImpl caller,
      String[] results,
      float[] scores,
      boolean provisional) {
    assert nativeSpeechRecognizerImplAndroid != 0;
    GEN_JNI.org_chromium_content_browser_SpeechRecognitionImpl_onRecognitionResults(
        nativeSpeechRecognizerImplAndroid, caller, results, scores, provisional);
  }

  @Override
  public void onSoundEnd(long nativeSpeechRecognizerImplAndroid, SpeechRecognitionImpl caller) {
    assert nativeSpeechRecognizerImplAndroid != 0;
    GEN_JNI.org_chromium_content_browser_SpeechRecognitionImpl_onSoundEnd(
        nativeSpeechRecognizerImplAndroid, caller);
  }

  @Override
  public void onSoundStart(long nativeSpeechRecognizerImplAndroid, SpeechRecognitionImpl caller) {
    assert nativeSpeechRecognizerImplAndroid != 0;
    GEN_JNI.org_chromium_content_browser_SpeechRecognitionImpl_onSoundStart(
        nativeSpeechRecognizerImplAndroid, caller);
  }

  public static SpeechRecognitionImpl.Natives get() {
    if (GEN_JNI.TESTING_ENABLED) {
      if (testInstance != null) {
        return testInstance;
      }
      if (GEN_JNI.REQUIRE_MOCK) {
        throw new UnsupportedOperationException(
            "No mock found for the native implementation of SpeechRecognitionImpl.Natives. "
                + "The current configuration requires implementations be mocked.");
      }
    }
    NativeLibraryLoadedStatus.checkLoaded();
    return new SpeechRecognitionImplJni();
  }
}
