// CssSampleId.java is auto generated by mojom_bindings_generator.py, do not edit

// Copyright 2014 The Chromium Authors
// Use of this source code is governed by a BSD-style license that can be
// found in the LICENSE file.

// This file is autogenerated by:
//     mojo/public/tools/bindings/mojom_bindings_generator.py
// For:
//     third_party/blink/public/mojom/use_counter/metrics/css_property_id.mojom
//

package org.chromium.blink.mojom;

import androidx.annotation.IntDef;

public final class CssSampleId {
  private static final boolean IS_EXTENSIBLE = false;

  @IntDef({
    CssSampleId.INVALID,
    CssSampleId.INTERNAL_ALIGN_CONTENT_BLOCK,
    CssSampleId.INTERNAL_ALIGN_SELF_BLOCK,
    CssSampleId.INTERNAL_EMPTY_LINE_HEIGHT,
    CssSampleId.INTERNAL_VISITED_BACKGROUND_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_BLOCK_END_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_BLOCK_START_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_BOTTOM_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_INLINE_END_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_INLINE_START_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_LEFT_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_RIGHT_COLOR,
    CssSampleId.INTERNAL_VISITED_BORDER_TOP_COLOR,
    CssSampleId.INTERNAL_VISITED_CARET_COLOR,
    CssSampleId.INTERNAL_VISITED_COLOR,
    CssSampleId.INTERNAL_VISITED_COLUMN_RULE_COLOR,
    CssSampleId.INTERNAL_VISITED_FILL,
    CssSampleId.INTERNAL_VISITED_OUTLINE_COLOR,
    CssSampleId.INTERNAL_VISITED_STROKE,
    CssSampleId.INTERNAL_VISITED_TEXT_DECORATION_COLOR,
    CssSampleId.INTERNAL_VISITED_TEXT_EMPHASIS_COLOR,
    CssSampleId.INTERNAL_VISITED_TEXT_FILL_COLOR,
    CssSampleId.INTERNAL_VISITED_TEXT_STROKE_COLOR,
    CssSampleId.INTERNAL_FONT_SIZE_DELTA,
    CssSampleId.INTERNAL_FORCED_BACKGROUND_COLOR,
    CssSampleId.INTERNAL_FORCED_BORDER_COLOR,
    CssSampleId.INTERNAL_FORCED_COLOR,
    CssSampleId.INTERNAL_FORCED_OUTLINE_COLOR,
    CssSampleId.INTERNAL_FORCED_VISITED_COLOR,
    CssSampleId.INTERNAL_OVERFLOW_BLOCK,
    CssSampleId.INTERNAL_OVERFLOW_INLINE,
    CssSampleId.TOTAL_PAGES_MEASURED,
    CssSampleId.COLOR,
    CssSampleId.DIRECTION,
    CssSampleId.DISPLAY,
    CssSampleId.FONT,
    CssSampleId.FONT_FAMILY,
    CssSampleId.FONT_SIZE,
    CssSampleId.FONT_STYLE,
    CssSampleId.FONT_VARIANT,
    CssSampleId.FONT_WEIGHT,
    CssSampleId.TEXT_RENDERING,
    CssSampleId.ALIAS_WEBKIT_FONT_FEATURE_SETTINGS,
    CssSampleId.FONT_KERNING,
    CssSampleId.WEBKIT_FONT_SMOOTHING,
    CssSampleId.FONT_VARIANT_LIGATURES,
    CssSampleId.WEBKIT_LOCALE,
    CssSampleId.WEBKIT_TEXT_ORIENTATION,
    CssSampleId.WEBKIT_WRITING_MODE,
    CssSampleId.ZOOM,
    CssSampleId.LINE_HEIGHT,
    CssSampleId.BACKGROUND,
    CssSampleId.BACKGROUND_ATTACHMENT,
    CssSampleId.BACKGROUND_CLIP,
    CssSampleId.BACKGROUND_COLOR,
    CssSampleId.BACKGROUND_IMAGE,
    CssSampleId.BACKGROUND_ORIGIN,
    CssSampleId.BACKGROUND_POSITION,
    CssSampleId.BACKGROUND_POSITION_X,
    CssSampleId.BACKGROUND_POSITION_Y,
    CssSampleId.BACKGROUND_REPEAT,
    CssSampleId.BACKGROUND_SIZE,
    CssSampleId.BORDER,
    CssSampleId.BORDER_BOTTOM,
    CssSampleId.BORDER_BOTTOM_COLOR,
    CssSampleId.BORDER_BOTTOM_LEFT_RADIUS,
    CssSampleId.BORDER_BOTTOM_RIGHT_RADIUS,
    CssSampleId.BORDER_BOTTOM_STYLE,
    CssSampleId.BORDER_BOTTOM_WIDTH,
    CssSampleId.BORDER_COLLAPSE,
    CssSampleId.BORDER_COLOR,
    CssSampleId.BORDER_IMAGE,
    CssSampleId.BORDER_IMAGE_OUTSET,
    CssSampleId.BORDER_IMAGE_REPEAT,
    CssSampleId.BORDER_IMAGE_SLICE,
    CssSampleId.BORDER_IMAGE_SOURCE,
    CssSampleId.BORDER_IMAGE_WIDTH,
    CssSampleId.BORDER_LEFT,
    CssSampleId.BORDER_LEFT_COLOR,
    CssSampleId.BORDER_LEFT_STYLE,
    CssSampleId.BORDER_LEFT_WIDTH,
    CssSampleId.BORDER_RADIUS,
    CssSampleId.BORDER_RIGHT,
    CssSampleId.BORDER_RIGHT_COLOR,
    CssSampleId.BORDER_RIGHT_STYLE,
    CssSampleId.BORDER_RIGHT_WIDTH,
    CssSampleId.BORDER_SPACING,
    CssSampleId.BORDER_STYLE,
    CssSampleId.BORDER_TOP,
    CssSampleId.BORDER_TOP_COLOR,
    CssSampleId.BORDER_TOP_LEFT_RADIUS,
    CssSampleId.BORDER_TOP_RIGHT_RADIUS,
    CssSampleId.BORDER_TOP_STYLE,
    CssSampleId.BORDER_TOP_WIDTH,
    CssSampleId.BORDER_WIDTH,
    CssSampleId.BOTTOM,
    CssSampleId.BOX_SHADOW,
    CssSampleId.BOX_SIZING,
    CssSampleId.CAPTION_SIDE,
    CssSampleId.CLEAR,
    CssSampleId.CLIP,
    CssSampleId.ALIAS_WEBKIT_CLIP_PATH,
    CssSampleId.CONTENT,
    CssSampleId.COUNTER_INCREMENT,
    CssSampleId.COUNTER_RESET,
    CssSampleId.CURSOR,
    CssSampleId.EMPTY_CELLS,
    CssSampleId.FLOAT,
    CssSampleId.FONT_STRETCH,
    CssSampleId.HEIGHT,
    CssSampleId.IMAGE_RENDERING,
    CssSampleId.LEFT,
    CssSampleId.LETTER_SPACING,
    CssSampleId.LIST_STYLE,
    CssSampleId.LIST_STYLE_IMAGE,
    CssSampleId.LIST_STYLE_POSITION,
    CssSampleId.LIST_STYLE_TYPE,
    CssSampleId.MARGIN,
    CssSampleId.MARGIN_BOTTOM,
    CssSampleId.MARGIN_LEFT,
    CssSampleId.MARGIN_RIGHT,
    CssSampleId.MARGIN_TOP,
    CssSampleId.MAX_HEIGHT,
    CssSampleId.MAX_WIDTH,
    CssSampleId.MIN_HEIGHT,
    CssSampleId.MIN_WIDTH,
    CssSampleId.OPACITY,
    CssSampleId.ORPHANS,
    CssSampleId.OUTLINE,
    CssSampleId.OUTLINE_COLOR,
    CssSampleId.OUTLINE_OFFSET,
    CssSampleId.OUTLINE_STYLE,
    CssSampleId.OUTLINE_WIDTH,
    CssSampleId.OVERFLOW,
    CssSampleId.OVERFLOW_WRAP,
    CssSampleId.OVERFLOW_X,
    CssSampleId.OVERFLOW_Y,
    CssSampleId.PADDING,
    CssSampleId.PADDING_BOTTOM,
    CssSampleId.PADDING_LEFT,
    CssSampleId.PADDING_RIGHT,
    CssSampleId.PADDING_TOP,
    CssSampleId.PAGE,
    CssSampleId.PAGE_BREAK_AFTER,
    CssSampleId.PAGE_BREAK_BEFORE,
    CssSampleId.PAGE_BREAK_INSIDE,
    CssSampleId.POINTER_EVENTS,
    CssSampleId.POSITION,
    CssSampleId.QUOTES,
    CssSampleId.RESIZE,
    CssSampleId.RIGHT,
    CssSampleId.SIZE,
    CssSampleId.SRC,
    CssSampleId.SPEAK,
    CssSampleId.TABLE_LAYOUT,
    CssSampleId.TAB_SIZE,
    CssSampleId.TEXT_ALIGN,
    CssSampleId.TEXT_DECORATION,
    CssSampleId.TEXT_INDENT,
    CssSampleId.TEXT_OVERFLOW,
    CssSampleId.TEXT_SHADOW,
    CssSampleId.TEXT_TRANSFORM,
    CssSampleId.TOP,
    CssSampleId.TRANSITION,
    CssSampleId.TRANSITION_DELAY,
    CssSampleId.TRANSITION_DURATION,
    CssSampleId.TRANSITION_PROPERTY,
    CssSampleId.TRANSITION_TIMING_FUNCTION,
    CssSampleId.UNICODE_BIDI,
    CssSampleId.UNICODE_RANGE,
    CssSampleId.VERTICAL_ALIGN,
    CssSampleId.VISIBILITY,
    CssSampleId.WHITE_SPACE,
    CssSampleId.WIDOWS,
    CssSampleId.WIDTH,
    CssSampleId.WORD_BREAK,
    CssSampleId.WORD_SPACING,
    CssSampleId.ALIAS_WORD_WRAP,
    CssSampleId.Z_INDEX,
    CssSampleId.ALIAS_WEBKIT_ANIMATION,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_DELAY,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_DIRECTION,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_DURATION,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_FILL_MODE,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_ITERATION_COUNT,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_NAME,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_PLAY_STATE,
    CssSampleId.ALIAS_WEBKIT_ANIMATION_TIMING_FUNCTION,
    CssSampleId.ALIAS_WEBKIT_APPEARANCE,
    CssSampleId.ALIAS_WEBKIT_BACKFACE_VISIBILITY,
    CssSampleId.ALIAS_WEBKIT_BACKGROUND_CLIP,
    CssSampleId.ALIAS_WEBKIT_BACKGROUND_ORIGIN,
    CssSampleId.ALIAS_WEBKIT_BACKGROUND_SIZE,
    CssSampleId.ALIAS_WEBKIT_BORDER_AFTER,
    CssSampleId.ALIAS_WEBKIT_BORDER_AFTER_COLOR,
    CssSampleId.ALIAS_WEBKIT_BORDER_AFTER_STYLE,
    CssSampleId.ALIAS_WEBKIT_BORDER_AFTER_WIDTH,
    CssSampleId.ALIAS_WEBKIT_BORDER_BEFORE,
    CssSampleId.ALIAS_WEBKIT_BORDER_BEFORE_COLOR,
    CssSampleId.ALIAS_WEBKIT_BORDER_BEFORE_STYLE,
    CssSampleId.ALIAS_WEBKIT_BORDER_BEFORE_WIDTH,
    CssSampleId.ALIAS_WEBKIT_BORDER_END,
    CssSampleId.ALIAS_WEBKIT_BORDER_END_COLOR,
    CssSampleId.ALIAS_WEBKIT_BORDER_END_STYLE,
    CssSampleId.ALIAS_WEBKIT_BORDER_END_WIDTH,
    CssSampleId.WEBKIT_BORDER_HORIZONTAL_SPACING,
    CssSampleId.WEBKIT_BORDER_IMAGE,
    CssSampleId.ALIAS_WEBKIT_BORDER_RADIUS,
    CssSampleId.ALIAS_WEBKIT_BORDER_START,
    CssSampleId.ALIAS_WEBKIT_BORDER_START_COLOR,
    CssSampleId.ALIAS_WEBKIT_BORDER_START_STYLE,
    CssSampleId.ALIAS_WEBKIT_BORDER_START_WIDTH,
    CssSampleId.WEBKIT_BORDER_VERTICAL_SPACING,
    CssSampleId.WEBKIT_BOX_ALIGN,
    CssSampleId.WEBKIT_BOX_DIRECTION,
    CssSampleId.WEBKIT_BOX_FLEX,
    CssSampleId.WEBKIT_BOX_ORDINAL_GROUP,
    CssSampleId.WEBKIT_BOX_ORIENT,
    CssSampleId.WEBKIT_BOX_PACK,
    CssSampleId.WEBKIT_BOX_REFLECT,
    CssSampleId.ALIAS_WEBKIT_BOX_SHADOW,
    CssSampleId.WEBKIT_COLUMN_BREAK_AFTER,
    CssSampleId.WEBKIT_COLUMN_BREAK_BEFORE,
    CssSampleId.WEBKIT_COLUMN_BREAK_INSIDE,
    CssSampleId.ALIAS_WEBKIT_COLUMN_COUNT,
    CssSampleId.ALIAS_WEBKIT_COLUMN_GAP,
    CssSampleId.ALIAS_WEBKIT_COLUMN_RULE,
    CssSampleId.ALIAS_WEBKIT_COLUMN_RULE_COLOR,
    CssSampleId.ALIAS_WEBKIT_COLUMN_RULE_STYLE,
    CssSampleId.ALIAS_WEBKIT_COLUMN_RULE_WIDTH,
    CssSampleId.ALIAS_WEBKIT_COLUMN_SPAN,
    CssSampleId.ALIAS_WEBKIT_COLUMN_WIDTH,
    CssSampleId.ALIAS_WEBKIT_COLUMNS,
    CssSampleId.ALIGN_CONTENT,
    CssSampleId.ALIGN_ITEMS,
    CssSampleId.ALIGN_SELF,
    CssSampleId.FLEX,
    CssSampleId.FLEX_BASIS,
    CssSampleId.FLEX_DIRECTION,
    CssSampleId.FLEX_FLOW,
    CssSampleId.FLEX_GROW,
    CssSampleId.FLEX_SHRINK,
    CssSampleId.FLEX_WRAP,
    CssSampleId.JUSTIFY_CONTENT,
    CssSampleId.GRID_TEMPLATE_COLUMNS,
    CssSampleId.GRID_TEMPLATE_ROWS,
    CssSampleId.GRID_COLUMN_START,
    CssSampleId.GRID_COLUMN_END,
    CssSampleId.GRID_ROW_START,
    CssSampleId.GRID_ROW_END,
    CssSampleId.GRID_COLUMN,
    CssSampleId.GRID_ROW,
    CssSampleId.GRID_AUTO_FLOW,
    CssSampleId.ALIAS_WEBKIT_HYPHENATE_CHARACTER,
    CssSampleId.WEBKIT_LINE_BREAK,
    CssSampleId.WEBKIT_LINE_CLAMP,
    CssSampleId.ALIAS_WEBKIT_LOGICAL_WIDTH,
    CssSampleId.ALIAS_WEBKIT_LOGICAL_HEIGHT,
    CssSampleId.WEBKIT_MARGIN_AFTER_COLLAPSE,
    CssSampleId.WEBKIT_MARGIN_BEFORE_COLLAPSE,
    CssSampleId.WEBKIT_MARGIN_BOTTOM_COLLAPSE,
    CssSampleId.WEBKIT_MARGIN_TOP_COLLAPSE,
    CssSampleId.WEBKIT_MARGIN_COLLAPSE,
    CssSampleId.ALIAS_WEBKIT_MARGIN_AFTER,
    CssSampleId.ALIAS_WEBKIT_MARGIN_BEFORE,
    CssSampleId.ALIAS_WEBKIT_MARGIN_END,
    CssSampleId.ALIAS_WEBKIT_MARGIN_START,
    CssSampleId.WEBKIT_MASK,
    CssSampleId.WEBKIT_MASK_BOX_IMAGE,
    CssSampleId.WEBKIT_MASK_BOX_IMAGE_OUTSET,
    CssSampleId.WEBKIT_MASK_BOX_IMAGE_REPEAT,
    CssSampleId.WEBKIT_MASK_BOX_IMAGE_SLICE,
    CssSampleId.WEBKIT_MASK_BOX_IMAGE_SOURCE,
    CssSampleId.WEBKIT_MASK_BOX_IMAGE_WIDTH,
    CssSampleId.WEBKIT_MASK_CLIP,
    CssSampleId.WEBKIT_MASK_COMPOSITE,
    CssSampleId.WEBKIT_MASK_IMAGE,
    CssSampleId.WEBKIT_MASK_ORIGIN,
    CssSampleId.WEBKIT_MASK_POSITION,
    CssSampleId.WEBKIT_MASK_POSITION_X,
    CssSampleId.WEBKIT_MASK_POSITION_Y,
    CssSampleId.WEBKIT_MASK_REPEAT,
    CssSampleId.WEBKIT_MASK_SIZE,
    CssSampleId.ALIAS_WEBKIT_MAX_LOGICAL_WIDTH,
    CssSampleId.ALIAS_WEBKIT_MAX_LOGICAL_HEIGHT,
    CssSampleId.ALIAS_WEBKIT_MIN_LOGICAL_WIDTH,
    CssSampleId.ALIAS_WEBKIT_MIN_LOGICAL_HEIGHT,
    CssSampleId.ORDER,
    CssSampleId.ALIAS_WEBKIT_PADDING_AFTER,
    CssSampleId.ALIAS_WEBKIT_PADDING_BEFORE,
    CssSampleId.ALIAS_WEBKIT_PADDING_END,
    CssSampleId.ALIAS_WEBKIT_PADDING_START,
    CssSampleId.ALIAS_WEBKIT_PERSPECTIVE,
    CssSampleId.ALIAS_WEBKIT_PERSPECTIVE_ORIGIN,
    CssSampleId.WEBKIT_PERSPECTIVE_ORIGIN_X,
    CssSampleId.WEBKIT_PERSPECTIVE_ORIGIN_Y,
    CssSampleId.WEBKIT_PRINT_COLOR_ADJUST,
    CssSampleId.WEBKIT_RTL_ORDERING,
    CssSampleId.WEBKIT_RUBY_POSITION,
    CssSampleId.WEBKIT_TEXT_COMBINE,
    CssSampleId.WEBKIT_TEXT_DECORATIONS_IN_EFFECT,
    CssSampleId.ALIAS_WEBKIT_TEXT_EMPHASIS,
    CssSampleId.ALIAS_WEBKIT_TEXT_EMPHASIS_COLOR,
    CssSampleId.ALIAS_WEBKIT_TEXT_EMPHASIS_POSITION,
    CssSampleId.ALIAS_WEBKIT_TEXT_EMPHASIS_STYLE,
    CssSampleId.WEBKIT_TEXT_FILL_COLOR,
    CssSampleId.WEBKIT_TEXT_SECURITY,
    CssSampleId.WEBKIT_TEXT_STROKE,
    CssSampleId.WEBKIT_TEXT_STROKE_COLOR,
    CssSampleId.WEBKIT_TEXT_STROKE_WIDTH,
    CssSampleId.ALIAS_WEBKIT_TRANSFORM,
    CssSampleId.ALIAS_WEBKIT_TRANSFORM_ORIGIN,
    CssSampleId.WEBKIT_TRANSFORM_ORIGIN_X,
    CssSampleId.WEBKIT_TRANSFORM_ORIGIN_Y,
    CssSampleId.WEBKIT_TRANSFORM_ORIGIN_Z,
    CssSampleId.ALIAS_WEBKIT_TRANSFORM_STYLE,
    CssSampleId.ALIAS_WEBKIT_TRANSITION,
    CssSampleId.ALIAS_WEBKIT_TRANSITION_DELAY,
    CssSampleId.ALIAS_WEBKIT_TRANSITION_DURATION,
    CssSampleId.ALIAS_WEBKIT_TRANSITION_PROPERTY,
    CssSampleId.ALIAS_WEBKIT_TRANSITION_TIMING_FUNCTION,
    CssSampleId.WEBKIT_USER_DRAG,
    CssSampleId.WEBKIT_USER_MODIFY,
    CssSampleId.ALIAS_WEBKIT_USER_SELECT,
    CssSampleId.SHAPE_OUTSIDE,
    CssSampleId.SHAPE_MARGIN,
    CssSampleId.CLIP_PATH,
    CssSampleId.CLIP_RULE,
    CssSampleId.MASK,
    CssSampleId.FILTER,
    CssSampleId.FLOOD_COLOR,
    CssSampleId.FLOOD_OPACITY,
    CssSampleId.LIGHTING_COLOR,
    CssSampleId.STOP_COLOR,
    CssSampleId.STOP_OPACITY,
    CssSampleId.COLOR_INTERPOLATION,
    CssSampleId.COLOR_INTERPOLATION_FILTERS,
    CssSampleId.COLOR_RENDERING,
    CssSampleId.FILL,
    CssSampleId.FILL_OPACITY,
    CssSampleId.FILL_RULE,
    CssSampleId.MARKER,
    CssSampleId.MARKER_END,
    CssSampleId.MARKER_MID,
    CssSampleId.MARKER_START,
    CssSampleId.MASK_TYPE,
    CssSampleId.SHAPE_RENDERING,
    CssSampleId.STROKE,
    CssSampleId.STROKE_DASHARRAY,
    CssSampleId.STROKE_DASHOFFSET,
    CssSampleId.STROKE_LINECAP,
    CssSampleId.STROKE_LINEJOIN,
    CssSampleId.STROKE_MITERLIMIT,
    CssSampleId.STROKE_OPACITY,
    CssSampleId.STROKE_WIDTH,
    CssSampleId.ALIGNMENT_BASELINE,
    CssSampleId.BASELINE_SHIFT,
    CssSampleId.DOMINANT_BASELINE,
    CssSampleId.TEXT_ANCHOR,
    CssSampleId.VECTOR_EFFECT,
    CssSampleId.WRITING_MODE,
    CssSampleId.TEXT_DECORATION_LINE,
    CssSampleId.TEXT_DECORATION_STYLE,
    CssSampleId.TEXT_DECORATION_COLOR,
    CssSampleId.TEXT_ALIGN_LAST,
    CssSampleId.TEXT_UNDERLINE_POSITION,
    CssSampleId.MAX_ZOOM,
    CssSampleId.MIN_ZOOM,
    CssSampleId.ORIENTATION,
    CssSampleId.USER_ZOOM,
    CssSampleId.ALIAS_WEBKIT_APP_REGION,
    CssSampleId.ALIAS_WEBKIT_FILTER,
    CssSampleId.WEBKIT_BOX_DECORATION_BREAK,
    CssSampleId.WEBKIT_TAP_HIGHLIGHT_COLOR,
    CssSampleId.BUFFERED_RENDERING,
    CssSampleId.GRID_AUTO_ROWS,
    CssSampleId.GRID_AUTO_COLUMNS,
    CssSampleId.BACKGROUND_BLEND_MODE,
    CssSampleId.MIX_BLEND_MODE,
    CssSampleId.TOUCH_ACTION,
    CssSampleId.GRID_AREA,
    CssSampleId.GRID_TEMPLATE_AREAS,
    CssSampleId.ANIMATION,
    CssSampleId.ANIMATION_DELAY,
    CssSampleId.ANIMATION_DIRECTION,
    CssSampleId.ANIMATION_DURATION,
    CssSampleId.ANIMATION_FILL_MODE,
    CssSampleId.ANIMATION_ITERATION_COUNT,
    CssSampleId.ANIMATION_NAME,
    CssSampleId.ANIMATION_PLAY_STATE,
    CssSampleId.ANIMATION_TIMING_FUNCTION,
    CssSampleId.OBJECT_FIT,
    CssSampleId.PAINT_ORDER,
    CssSampleId.MASK_SOURCE_TYPE,
    CssSampleId.ISOLATION,
    CssSampleId.OBJECT_POSITION,
    CssSampleId.SHAPE_IMAGE_THRESHOLD,
    CssSampleId.COLUMN_FILL,
    CssSampleId.TEXT_JUSTIFY,
    CssSampleId.JUSTIFY_SELF,
    CssSampleId.SCROLL_BEHAVIOR,
    CssSampleId.WILL_CHANGE,
    CssSampleId.TRANSFORM,
    CssSampleId.TRANSFORM_ORIGIN,
    CssSampleId.TRANSFORM_STYLE,
    CssSampleId.PERSPECTIVE,
    CssSampleId.PERSPECTIVE_ORIGIN,
    CssSampleId.BACKFACE_VISIBILITY,
    CssSampleId.GRID_TEMPLATE,
    CssSampleId.GRID,
    CssSampleId.ALL,
    CssSampleId.JUSTIFY_ITEMS,
    CssSampleId.X,
    CssSampleId.Y,
    CssSampleId.RX,
    CssSampleId.RY,
    CssSampleId.FONT_SIZE_ADJUST,
    CssSampleId.CX,
    CssSampleId.CY,
    CssSampleId.R,
    CssSampleId.ALIAS_EPUB_CAPTION_SIDE,
    CssSampleId.ALIAS_EPUB_TEXT_COMBINE,
    CssSampleId.ALIAS_EPUB_TEXT_EMPHASIS,
    CssSampleId.ALIAS_EPUB_TEXT_EMPHASIS_COLOR,
    CssSampleId.ALIAS_EPUB_TEXT_EMPHASIS_STYLE,
    CssSampleId.ALIAS_EPUB_TEXT_ORIENTATION,
    CssSampleId.ALIAS_EPUB_TEXT_TRANSFORM,
    CssSampleId.ALIAS_EPUB_WORD_BREAK,
    CssSampleId.ALIAS_EPUB_WRITING_MODE,
    CssSampleId.ALIAS_WEBKIT_ALIGN_CONTENT,
    CssSampleId.ALIAS_WEBKIT_ALIGN_ITEMS,
    CssSampleId.ALIAS_WEBKIT_ALIGN_SELF,
    CssSampleId.ALIAS_WEBKIT_BORDER_BOTTOM_LEFT_RADIUS,
    CssSampleId.ALIAS_WEBKIT_BORDER_BOTTOM_RIGHT_RADIUS,
    CssSampleId.ALIAS_WEBKIT_BORDER_TOP_LEFT_RADIUS,
    CssSampleId.ALIAS_WEBKIT_BORDER_TOP_RIGHT_RADIUS,
    CssSampleId.ALIAS_WEBKIT_BOX_SIZING,
    CssSampleId.ALIAS_WEBKIT_FLEX,
    CssSampleId.ALIAS_WEBKIT_FLEX_BASIS,
    CssSampleId.ALIAS_WEBKIT_FLEX_DIRECTION,
    CssSampleId.ALIAS_WEBKIT_FLEX_FLOW,
    CssSampleId.ALIAS_WEBKIT_FLEX_GROW,
    CssSampleId.ALIAS_WEBKIT_FLEX_SHRINK,
    CssSampleId.ALIAS_WEBKIT_FLEX_WRAP,
    CssSampleId.ALIAS_WEBKIT_JUSTIFY_CONTENT,
    CssSampleId.ALIAS_WEBKIT_OPACITY,
    CssSampleId.ALIAS_WEBKIT_ORDER,
    CssSampleId.ALIAS_WEBKIT_SHAPE_IMAGE_THRESHOLD,
    CssSampleId.ALIAS_WEBKIT_SHAPE_MARGIN,
    CssSampleId.ALIAS_WEBKIT_SHAPE_OUTSIDE,
    CssSampleId.SCROLL_SNAP_TYPE,
    CssSampleId.TRANSLATE,
    CssSampleId.ROTATE,
    CssSampleId.SCALE,
    CssSampleId.IMAGE_ORIENTATION,
    CssSampleId.BACKDROP_FILTER,
    CssSampleId.TEXT_COMBINE_UPRIGHT,
    CssSampleId.TEXT_ORIENTATION,
    CssSampleId.GRID_COLUMN_GAP,
    CssSampleId.GRID_ROW_GAP,
    CssSampleId.GRID_GAP,
    CssSampleId.FONT_FEATURE_SETTINGS,
    CssSampleId.VARIABLE,
    CssSampleId.FONT_DISPLAY,
    CssSampleId.CONTAIN,
    CssSampleId.D,
    CssSampleId.BREAK_AFTER,
    CssSampleId.BREAK_BEFORE,
    CssSampleId.BREAK_INSIDE,
    CssSampleId.COLUMN_COUNT,
    CssSampleId.COLUMN_GAP,
    CssSampleId.COLUMN_RULE,
    CssSampleId.COLUMN_RULE_COLOR,
    CssSampleId.COLUMN_RULE_STYLE,
    CssSampleId.COLUMN_RULE_WIDTH,
    CssSampleId.COLUMN_SPAN,
    CssSampleId.COLUMN_WIDTH,
    CssSampleId.COLUMNS,
    CssSampleId.FONT_VARIANT_CAPS,
    CssSampleId.HYPHENS,
    CssSampleId.FONT_VARIANT_NUMERIC,
    CssSampleId.TEXT_SIZE_ADJUST,
    CssSampleId.ALIAS_WEBKIT_TEXT_SIZE_ADJUST,
    CssSampleId.OVERFLOW_ANCHOR,
    CssSampleId.USER_SELECT,
    CssSampleId.OFFSET_DISTANCE,
    CssSampleId.OFFSET_PATH,
    CssSampleId.OFFSET,
    CssSampleId.OFFSET_ANCHOR,
    CssSampleId.OFFSET_POSITION,
    CssSampleId.CARET_COLOR,
    CssSampleId.OFFSET_ROTATE,
    CssSampleId.FONT_VARIATION_SETTINGS,
    CssSampleId.INLINE_SIZE,
    CssSampleId.BLOCK_SIZE,
    CssSampleId.MIN_INLINE_SIZE,
    CssSampleId.MIN_BLOCK_SIZE,
    CssSampleId.MAX_INLINE_SIZE,
    CssSampleId.MAX_BLOCK_SIZE,
    CssSampleId.LINE_BREAK,
    CssSampleId.PLACE_CONTENT,
    CssSampleId.PLACE_ITEMS,
    CssSampleId.TRANSFORM_BOX,
    CssSampleId.PLACE_SELF,
    CssSampleId.SCROLL_SNAP_ALIGN,
    CssSampleId.SCROLL_PADDING,
    CssSampleId.SCROLL_PADDING_TOP,
    CssSampleId.SCROLL_PADDING_RIGHT,
    CssSampleId.SCROLL_PADDING_BOTTOM,
    CssSampleId.SCROLL_PADDING_LEFT,
    CssSampleId.SCROLL_PADDING_BLOCK,
    CssSampleId.SCROLL_PADDING_BLOCK_START,
    CssSampleId.SCROLL_PADDING_BLOCK_END,
    CssSampleId.SCROLL_PADDING_INLINE,
    CssSampleId.SCROLL_PADDING_INLINE_START,
    CssSampleId.SCROLL_PADDING_INLINE_END,
    CssSampleId.SCROLL_MARGIN,
    CssSampleId.SCROLL_MARGIN_TOP,
    CssSampleId.SCROLL_MARGIN_RIGHT,
    CssSampleId.SCROLL_MARGIN_BOTTOM,
    CssSampleId.SCROLL_MARGIN_LEFT,
    CssSampleId.SCROLL_MARGIN_BLOCK,
    CssSampleId.SCROLL_MARGIN_BLOCK_START,
    CssSampleId.SCROLL_MARGIN_BLOCK_END,
    CssSampleId.SCROLL_MARGIN_INLINE,
    CssSampleId.SCROLL_MARGIN_INLINE_START,
    CssSampleId.SCROLL_MARGIN_INLINE_END,
    CssSampleId.SCROLL_SNAP_STOP,
    CssSampleId.OVERSCROLL_BEHAVIOR,
    CssSampleId.OVERSCROLL_BEHAVIOR_X,
    CssSampleId.OVERSCROLL_BEHAVIOR_Y,
    CssSampleId.FONT_VARIANT_EAST_ASIAN,
    CssSampleId.TEXT_DECORATION_SKIP_INK,
    CssSampleId.SCROLL_CUSTOMIZATION,
    CssSampleId.ROW_GAP,
    CssSampleId.GAP,
    CssSampleId.VIEWPORT_FIT,
    CssSampleId.MARGIN_BLOCK_START,
    CssSampleId.MARGIN_BLOCK_END,
    CssSampleId.MARGIN_INLINE_START,
    CssSampleId.MARGIN_INLINE_END,
    CssSampleId.PADDING_BLOCK_START,
    CssSampleId.PADDING_BLOCK_END,
    CssSampleId.PADDING_INLINE_START,
    CssSampleId.PADDING_INLINE_END,
    CssSampleId.BORDER_BLOCK_END_COLOR,
    CssSampleId.BORDER_BLOCK_END_STYLE,
    CssSampleId.BORDER_BLOCK_END_WIDTH,
    CssSampleId.BORDER_BLOCK_START_COLOR,
    CssSampleId.BORDER_BLOCK_START_STYLE,
    CssSampleId.BORDER_BLOCK_START_WIDTH,
    CssSampleId.BORDER_INLINE_END_COLOR,
    CssSampleId.BORDER_INLINE_END_STYLE,
    CssSampleId.BORDER_INLINE_END_WIDTH,
    CssSampleId.BORDER_INLINE_START_COLOR,
    CssSampleId.BORDER_INLINE_START_STYLE,
    CssSampleId.BORDER_INLINE_START_WIDTH,
    CssSampleId.BORDER_BLOCK_START,
    CssSampleId.BORDER_BLOCK_END,
    CssSampleId.BORDER_INLINE_START,
    CssSampleId.BORDER_INLINE_END,
    CssSampleId.MARGIN_BLOCK,
    CssSampleId.MARGIN_INLINE,
    CssSampleId.PADDING_BLOCK,
    CssSampleId.PADDING_INLINE,
    CssSampleId.BORDER_BLOCK_COLOR,
    CssSampleId.BORDER_BLOCK_STYLE,
    CssSampleId.BORDER_BLOCK_WIDTH,
    CssSampleId.BORDER_INLINE_COLOR,
    CssSampleId.BORDER_INLINE_STYLE,
    CssSampleId.BORDER_INLINE_WIDTH,
    CssSampleId.BORDER_BLOCK,
    CssSampleId.BORDER_INLINE,
    CssSampleId.INSET_BLOCK_START,
    CssSampleId.INSET_BLOCK_END,
    CssSampleId.INSET_BLOCK,
    CssSampleId.INSET_INLINE_START,
    CssSampleId.INSET_INLINE_END,
    CssSampleId.INSET_INLINE,
    CssSampleId.INSET,
    CssSampleId.COLOR_SCHEME,
    CssSampleId.OVERFLOW_INLINE,
    CssSampleId.OVERFLOW_BLOCK,
    CssSampleId.FORCED_COLOR_ADJUST,
    CssSampleId.INHERITS,
    CssSampleId.INITIAL_VALUE,
    CssSampleId.SYNTAX,
    CssSampleId.OVERSCROLL_BEHAVIOR_INLINE,
    CssSampleId.OVERSCROLL_BEHAVIOR_BLOCK,
    CssSampleId.FONT_OPTICAL_SIZING,
    CssSampleId.CONTAIN_INTRINSIC_BLOCK_SIZE,
    CssSampleId.CONTAIN_INTRINSIC_HEIGHT,
    CssSampleId.CONTAIN_INTRINSIC_INLINE_SIZE,
    CssSampleId.CONTAIN_INTRINSIC_SIZE,
    CssSampleId.CONTAIN_INTRINSIC_WIDTH,
    CssSampleId.ORIGIN_TRIAL_TEST_PROPERTY,
    CssSampleId.MATH_STYLE,
    CssSampleId.ASPECT_RATIO,
    CssSampleId.APPEARANCE,
    CssSampleId.RUBY_POSITION,
    CssSampleId.TEXT_UNDERLINE_OFFSET,
    CssSampleId.CONTENT_VISIBILITY,
    CssSampleId.TEXT_DECORATION_THICKNESS,
    CssSampleId.PAGE_ORIENTATION,
    CssSampleId.ANIMATION_TIMELINE,
    CssSampleId.COUNTER_SET,
    CssSampleId.SOURCE,
    CssSampleId.START,
    CssSampleId.END,
    CssSampleId.TIME_RANGE,
    CssSampleId.SCROLLBAR_GUTTER,
    CssSampleId.ASCENT_OVERRIDE,
    CssSampleId.DESCENT_OVERRIDE,
    CssSampleId.ADVANCE_OVERRIDE,
    CssSampleId.LINE_GAP_OVERRIDE,
    CssSampleId.MATH_SHIFT,
    CssSampleId.MATH_DEPTH,
    CssSampleId.OVERFLOW_CLIP_MARGIN,
    CssSampleId.SCROLLBAR_WIDTH,
    CssSampleId.SYSTEM,
    CssSampleId.NEGATIVE,
    CssSampleId.PREFIX,
    CssSampleId.SUFFIX,
    CssSampleId.RANGE,
    CssSampleId.PAD,
    CssSampleId.FALLBACK,
    CssSampleId.SYMBOLS,
    CssSampleId.ADDITIVE_SYMBOLS,
    CssSampleId.SPEAK_AS,
    CssSampleId.BORDER_START_START_RADIUS,
    CssSampleId.BORDER_START_END_RADIUS,
    CssSampleId.BORDER_END_START_RADIUS,
    CssSampleId.BORDER_END_END_RADIUS,
    CssSampleId.ACCENT_COLOR,
    CssSampleId.SIZE_ADJUST,
    CssSampleId.CONTAINER_NAME,
    CssSampleId.CONTAINER_TYPE,
    CssSampleId.CONTAINER,
    CssSampleId.FONT_SYNTHESIS_WEIGHT,
    CssSampleId.FONT_SYNTHESIS_STYLE,
    CssSampleId.APP_REGION,
    CssSampleId.FONT_SYNTHESIS_SMALL_CAPS,
    CssSampleId.FONT_SYNTHESIS,
    CssSampleId.TEXT_EMPHASIS,
    CssSampleId.TEXT_EMPHASIS_COLOR,
    CssSampleId.TEXT_EMPHASIS_POSITION,
    CssSampleId.TEXT_EMPHASIS_STYLE,
    CssSampleId.FONT_PALETTE,
    CssSampleId.BASE_PALETTE,
    CssSampleId.OVERRIDE_COLORS,
    CssSampleId.VIEW_TRANSITION_NAME,
    CssSampleId.OBJECT_VIEW_BOX,
    CssSampleId.OBJECT_OVERFLOW,
    CssSampleId.ANCHOR_NAME,
    CssSampleId.POSITION_FALLBACK,
    CssSampleId.POPOVER_SHOW_DELAY,
    CssSampleId.POPOVER_HIDE_DELAY,
    CssSampleId.HYPHENATE_CHARACTER,
    CssSampleId.SCROLL_TIMELINE,
    CssSampleId.SCROLL_TIMELINE_NAME,
    CssSampleId.SCROLL_TIMELINE_AXIS,
    CssSampleId.VIEW_TIMELINE,
    CssSampleId.VIEW_TIMELINE_AXIS,
    CssSampleId.VIEW_TIMELINE_INSET,
    CssSampleId.VIEW_TIMELINE_NAME,
    CssSampleId.INITIAL_LETTER,
    CssSampleId.HYPHENATE_LIMIT_CHARS,
    CssSampleId.ANIMATION_DELAY_START,
    CssSampleId.ANIMATION_DELAY_END,
    CssSampleId.FONT_VARIANT_POSITION,
    CssSampleId.FONT_VARIANT_ALTERNATES,
    CssSampleId.BASELINE_SOURCE,
    CssSampleId.ANIMATION_RANGE,
    CssSampleId.ANIMATION_RANGE_START,
    CssSampleId.ANIMATION_RANGE_END,
    CssSampleId.ANIMATION_COMPOSITION,
    CssSampleId.TOP_LAYER,
    CssSampleId.ANCHOR_DEFAULT,
    CssSampleId.TEXT_WRAP,
    CssSampleId.TEXT_BOX_TRIM,
    CssSampleId.OVERLAY,
    CssSampleId.WHITE_SPACE_COLLAPSE,
    CssSampleId.SCROLL_TIMELINE_ATTACHMENT,
    CssSampleId.VIEW_TIMELINE_ATTACHMENT,
    CssSampleId.SCROLL_START_BLOCK,
    CssSampleId.SCROLL_START_INLINE,
    CssSampleId.SCROLL_START_X,
    CssSampleId.SCROLL_START_Y,
    CssSampleId.SCROLL_START,
    CssSampleId.SCROLL_START_TARGET_BLOCK,
    CssSampleId.SCROLL_START_TARGET_INLINE,
    CssSampleId.SCROLL_START_TARGET_X,
    CssSampleId.SCROLL_START_TARGET_Y,
    CssSampleId.SCROLL_START_TARGET,
    CssSampleId.TIMELINE_SCOPE,
    CssSampleId.SCROLLBAR_COLOR,
    CssSampleId.POSITION_FALLBACK_BOUNDS,
    CssSampleId.TRANSITION_BEHAVIOR,
    CssSampleId.TEXT_AUTOSPACE,
    CssSampleId.NAVIGATION,
    CssSampleId.DYNAMIC_RANGE_LIMIT,
    CssSampleId.FIELD_SIZING,
    CssSampleId.TEXT_SPACING_TRIM,
    CssSampleId.MASK_IMAGE,
    CssSampleId.MASK_CLIP,
    CssSampleId.MASK_SIZE,
    CssSampleId.MASK_ORIGIN,
    CssSampleId.TEXT_SPACING,
    CssSampleId.MASK_REPEAT,
    CssSampleId.MASK_COMPOSITE,
    CssSampleId.MASK_POSITION,
    CssSampleId.MASK_MODE,
    CssSampleId.INSET_AREA,
    CssSampleId.VIEW_TRANSITION_CLASS,
    CssSampleId.POSITION_TRY_ORDER,
    CssSampleId.POSITION_TRY_OPTIONS,
    CssSampleId.POSITION_TRY
  })
  public @interface EnumType {}

  public static final int INVALID = 0;
  public static final int INTERNAL_ALIGN_CONTENT_BLOCK = 0;
  public static final int INTERNAL_ALIGN_SELF_BLOCK = 0;
  public static final int INTERNAL_EMPTY_LINE_HEIGHT = 0;
  public static final int INTERNAL_VISITED_BACKGROUND_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_BLOCK_END_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_BLOCK_START_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_BOTTOM_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_INLINE_END_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_INLINE_START_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_LEFT_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_RIGHT_COLOR = 0;
  public static final int INTERNAL_VISITED_BORDER_TOP_COLOR = 0;
  public static final int INTERNAL_VISITED_CARET_COLOR = 0;
  public static final int INTERNAL_VISITED_COLOR = 0;
  public static final int INTERNAL_VISITED_COLUMN_RULE_COLOR = 0;
  public static final int INTERNAL_VISITED_FILL = 0;
  public static final int INTERNAL_VISITED_OUTLINE_COLOR = 0;
  public static final int INTERNAL_VISITED_STROKE = 0;
  public static final int INTERNAL_VISITED_TEXT_DECORATION_COLOR = 0;
  public static final int INTERNAL_VISITED_TEXT_EMPHASIS_COLOR = 0;
  public static final int INTERNAL_VISITED_TEXT_FILL_COLOR = 0;
  public static final int INTERNAL_VISITED_TEXT_STROKE_COLOR = 0;
  public static final int INTERNAL_FONT_SIZE_DELTA = 0;
  public static final int INTERNAL_FORCED_BACKGROUND_COLOR = 0;
  public static final int INTERNAL_FORCED_BORDER_COLOR = 0;
  public static final int INTERNAL_FORCED_COLOR = 0;
  public static final int INTERNAL_FORCED_OUTLINE_COLOR = 0;
  public static final int INTERNAL_FORCED_VISITED_COLOR = 0;
  public static final int INTERNAL_OVERFLOW_BLOCK = 0;
  public static final int INTERNAL_OVERFLOW_INLINE = 0;
  public static final int TOTAL_PAGES_MEASURED = 1;
  public static final int COLOR = 2;
  public static final int DIRECTION = 3;
  public static final int DISPLAY = 4;
  public static final int FONT = 5;
  public static final int FONT_FAMILY = 6;
  public static final int FONT_SIZE = 7;
  public static final int FONT_STYLE = 8;
  public static final int FONT_VARIANT = 9;
  public static final int FONT_WEIGHT = 10;
  public static final int TEXT_RENDERING = 11;
  public static final int ALIAS_WEBKIT_FONT_FEATURE_SETTINGS = 12;
  public static final int FONT_KERNING = 13;
  public static final int WEBKIT_FONT_SMOOTHING = 14;
  public static final int FONT_VARIANT_LIGATURES = 15;
  public static final int WEBKIT_LOCALE = 16;
  public static final int WEBKIT_TEXT_ORIENTATION = 17;
  public static final int WEBKIT_WRITING_MODE = 18;
  public static final int ZOOM = 19;
  public static final int LINE_HEIGHT = 20;
  public static final int BACKGROUND = 21;
  public static final int BACKGROUND_ATTACHMENT = 22;
  public static final int BACKGROUND_CLIP = 23;
  public static final int BACKGROUND_COLOR = 24;
  public static final int BACKGROUND_IMAGE = 25;
  public static final int BACKGROUND_ORIGIN = 26;
  public static final int BACKGROUND_POSITION = 27;
  public static final int BACKGROUND_POSITION_X = 28;
  public static final int BACKGROUND_POSITION_Y = 29;
  public static final int BACKGROUND_REPEAT = 30;
  public static final int BACKGROUND_SIZE = 33;
  public static final int BORDER = 34;
  public static final int BORDER_BOTTOM = 35;
  public static final int BORDER_BOTTOM_COLOR = 36;
  public static final int BORDER_BOTTOM_LEFT_RADIUS = 37;
  public static final int BORDER_BOTTOM_RIGHT_RADIUS = 38;
  public static final int BORDER_BOTTOM_STYLE = 39;
  public static final int BORDER_BOTTOM_WIDTH = 40;
  public static final int BORDER_COLLAPSE = 41;
  public static final int BORDER_COLOR = 42;
  public static final int BORDER_IMAGE = 43;
  public static final int BORDER_IMAGE_OUTSET = 44;
  public static final int BORDER_IMAGE_REPEAT = 45;
  public static final int BORDER_IMAGE_SLICE = 46;
  public static final int BORDER_IMAGE_SOURCE = 47;
  public static final int BORDER_IMAGE_WIDTH = 48;
  public static final int BORDER_LEFT = 49;
  public static final int BORDER_LEFT_COLOR = 50;
  public static final int BORDER_LEFT_STYLE = 51;
  public static final int BORDER_LEFT_WIDTH = 52;
  public static final int BORDER_RADIUS = 53;
  public static final int BORDER_RIGHT = 54;
  public static final int BORDER_RIGHT_COLOR = 55;
  public static final int BORDER_RIGHT_STYLE = 56;
  public static final int BORDER_RIGHT_WIDTH = 57;
  public static final int BORDER_SPACING = 58;
  public static final int BORDER_STYLE = 59;
  public static final int BORDER_TOP = 60;
  public static final int BORDER_TOP_COLOR = 61;
  public static final int BORDER_TOP_LEFT_RADIUS = 62;
  public static final int BORDER_TOP_RIGHT_RADIUS = 63;
  public static final int BORDER_TOP_STYLE = 64;
  public static final int BORDER_TOP_WIDTH = 65;
  public static final int BORDER_WIDTH = 66;
  public static final int BOTTOM = 67;
  public static final int BOX_SHADOW = 68;
  public static final int BOX_SIZING = 69;
  public static final int CAPTION_SIDE = 70;
  public static final int CLEAR = 71;
  public static final int CLIP = 72;
  public static final int ALIAS_WEBKIT_CLIP_PATH = 73;
  public static final int CONTENT = 74;
  public static final int COUNTER_INCREMENT = 75;
  public static final int COUNTER_RESET = 76;
  public static final int CURSOR = 77;
  public static final int EMPTY_CELLS = 78;
  public static final int FLOAT = 79;
  public static final int FONT_STRETCH = 80;
  public static final int HEIGHT = 81;
  public static final int IMAGE_RENDERING = 82;
  public static final int LEFT = 83;
  public static final int LETTER_SPACING = 84;
  public static final int LIST_STYLE = 85;
  public static final int LIST_STYLE_IMAGE = 86;
  public static final int LIST_STYLE_POSITION = 87;
  public static final int LIST_STYLE_TYPE = 88;
  public static final int MARGIN = 89;
  public static final int MARGIN_BOTTOM = 90;
  public static final int MARGIN_LEFT = 91;
  public static final int MARGIN_RIGHT = 92;
  public static final int MARGIN_TOP = 93;
  public static final int MAX_HEIGHT = 94;
  public static final int MAX_WIDTH = 95;
  public static final int MIN_HEIGHT = 96;
  public static final int MIN_WIDTH = 97;
  public static final int OPACITY = 98;
  public static final int ORPHANS = 99;
  public static final int OUTLINE = 100;
  public static final int OUTLINE_COLOR = 101;
  public static final int OUTLINE_OFFSET = 102;
  public static final int OUTLINE_STYLE = 103;
  public static final int OUTLINE_WIDTH = 104;
  public static final int OVERFLOW = 105;
  public static final int OVERFLOW_WRAP = 106;
  public static final int OVERFLOW_X = 107;
  public static final int OVERFLOW_Y = 108;
  public static final int PADDING = 109;
  public static final int PADDING_BOTTOM = 110;
  public static final int PADDING_LEFT = 111;
  public static final int PADDING_RIGHT = 112;
  public static final int PADDING_TOP = 113;
  public static final int PAGE = 114;
  public static final int PAGE_BREAK_AFTER = 115;
  public static final int PAGE_BREAK_BEFORE = 116;
  public static final int PAGE_BREAK_INSIDE = 117;
  public static final int POINTER_EVENTS = 118;
  public static final int POSITION = 119;
  public static final int QUOTES = 120;
  public static final int RESIZE = 121;
  public static final int RIGHT = 122;
  public static final int SIZE = 123;
  public static final int SRC = 124;
  public static final int SPEAK = 125;
  public static final int TABLE_LAYOUT = 126;
  public static final int TAB_SIZE = 127;
  public static final int TEXT_ALIGN = 128;
  public static final int TEXT_DECORATION = 129;
  public static final int TEXT_INDENT = 130;
  public static final int TEXT_OVERFLOW = 136;
  public static final int TEXT_SHADOW = 142;
  public static final int TEXT_TRANSFORM = 143;
  public static final int TOP = 149;
  public static final int TRANSITION = 150;
  public static final int TRANSITION_DELAY = 151;
  public static final int TRANSITION_DURATION = 152;
  public static final int TRANSITION_PROPERTY = 153;
  public static final int TRANSITION_TIMING_FUNCTION = 154;
  public static final int UNICODE_BIDI = 155;
  public static final int UNICODE_RANGE = 156;
  public static final int VERTICAL_ALIGN = 157;
  public static final int VISIBILITY = 158;
  public static final int WHITE_SPACE = 159;
  public static final int WIDOWS = 160;
  public static final int WIDTH = 161;
  public static final int WORD_BREAK = 162;
  public static final int WORD_SPACING = 163;
  public static final int ALIAS_WORD_WRAP = 164;
  public static final int Z_INDEX = 165;
  public static final int ALIAS_WEBKIT_ANIMATION = 166;
  public static final int ALIAS_WEBKIT_ANIMATION_DELAY = 167;
  public static final int ALIAS_WEBKIT_ANIMATION_DIRECTION = 168;
  public static final int ALIAS_WEBKIT_ANIMATION_DURATION = 169;
  public static final int ALIAS_WEBKIT_ANIMATION_FILL_MODE = 170;
  public static final int ALIAS_WEBKIT_ANIMATION_ITERATION_COUNT = 171;
  public static final int ALIAS_WEBKIT_ANIMATION_NAME = 172;
  public static final int ALIAS_WEBKIT_ANIMATION_PLAY_STATE = 173;
  public static final int ALIAS_WEBKIT_ANIMATION_TIMING_FUNCTION = 174;
  public static final int ALIAS_WEBKIT_APPEARANCE = 175;
  public static final int ALIAS_WEBKIT_BACKFACE_VISIBILITY = 177;
  public static final int ALIAS_WEBKIT_BACKGROUND_CLIP = 178;
  public static final int ALIAS_WEBKIT_BACKGROUND_ORIGIN = 180;
  public static final int ALIAS_WEBKIT_BACKGROUND_SIZE = 181;
  public static final int ALIAS_WEBKIT_BORDER_AFTER = 182;
  public static final int ALIAS_WEBKIT_BORDER_AFTER_COLOR = 183;
  public static final int ALIAS_WEBKIT_BORDER_AFTER_STYLE = 184;
  public static final int ALIAS_WEBKIT_BORDER_AFTER_WIDTH = 185;
  public static final int ALIAS_WEBKIT_BORDER_BEFORE = 186;
  public static final int ALIAS_WEBKIT_BORDER_BEFORE_COLOR = 187;
  public static final int ALIAS_WEBKIT_BORDER_BEFORE_STYLE = 188;
  public static final int ALIAS_WEBKIT_BORDER_BEFORE_WIDTH = 189;
  public static final int ALIAS_WEBKIT_BORDER_END = 190;
  public static final int ALIAS_WEBKIT_BORDER_END_COLOR = 191;
  public static final int ALIAS_WEBKIT_BORDER_END_STYLE = 192;
  public static final int ALIAS_WEBKIT_BORDER_END_WIDTH = 193;
  public static final int WEBKIT_BORDER_HORIZONTAL_SPACING = 195;
  public static final int WEBKIT_BORDER_IMAGE = 196;
  public static final int ALIAS_WEBKIT_BORDER_RADIUS = 197;
  public static final int ALIAS_WEBKIT_BORDER_START = 198;
  public static final int ALIAS_WEBKIT_BORDER_START_COLOR = 199;
  public static final int ALIAS_WEBKIT_BORDER_START_STYLE = 200;
  public static final int ALIAS_WEBKIT_BORDER_START_WIDTH = 201;
  public static final int WEBKIT_BORDER_VERTICAL_SPACING = 202;
  public static final int WEBKIT_BOX_ALIGN = 203;
  public static final int WEBKIT_BOX_DIRECTION = 204;
  public static final int WEBKIT_BOX_FLEX = 205;
  public static final int WEBKIT_BOX_ORDINAL_GROUP = 208;
  public static final int WEBKIT_BOX_ORIENT = 209;
  public static final int WEBKIT_BOX_PACK = 210;
  public static final int WEBKIT_BOX_REFLECT = 211;
  public static final int ALIAS_WEBKIT_BOX_SHADOW = 212;
  public static final int WEBKIT_COLUMN_BREAK_AFTER = 215;
  public static final int WEBKIT_COLUMN_BREAK_BEFORE = 216;
  public static final int WEBKIT_COLUMN_BREAK_INSIDE = 217;
  public static final int ALIAS_WEBKIT_COLUMN_COUNT = 218;
  public static final int ALIAS_WEBKIT_COLUMN_GAP = 219;
  public static final int ALIAS_WEBKIT_COLUMN_RULE = 221;
  public static final int ALIAS_WEBKIT_COLUMN_RULE_COLOR = 222;
  public static final int ALIAS_WEBKIT_COLUMN_RULE_STYLE = 223;
  public static final int ALIAS_WEBKIT_COLUMN_RULE_WIDTH = 224;
  public static final int ALIAS_WEBKIT_COLUMN_SPAN = 225;
  public static final int ALIAS_WEBKIT_COLUMN_WIDTH = 226;
  public static final int ALIAS_WEBKIT_COLUMNS = 227;
  public static final int ALIGN_CONTENT = 230;
  public static final int ALIGN_ITEMS = 231;
  public static final int ALIGN_SELF = 232;
  public static final int FLEX = 233;
  public static final int FLEX_BASIS = 234;
  public static final int FLEX_DIRECTION = 235;
  public static final int FLEX_FLOW = 236;
  public static final int FLEX_GROW = 237;
  public static final int FLEX_SHRINK = 238;
  public static final int FLEX_WRAP = 239;
  public static final int JUSTIFY_CONTENT = 240;
  public static final int GRID_TEMPLATE_COLUMNS = 242;
  public static final int GRID_TEMPLATE_ROWS = 243;
  public static final int GRID_COLUMN_START = 244;
  public static final int GRID_COLUMN_END = 245;
  public static final int GRID_ROW_START = 246;
  public static final int GRID_ROW_END = 247;
  public static final int GRID_COLUMN = 248;
  public static final int GRID_ROW = 249;
  public static final int GRID_AUTO_FLOW = 250;
  public static final int ALIAS_WEBKIT_HYPHENATE_CHARACTER = 252;
  public static final int WEBKIT_LINE_BREAK = 259;
  public static final int WEBKIT_LINE_CLAMP = 260;
  public static final int ALIAS_WEBKIT_LOGICAL_WIDTH = 263;
  public static final int ALIAS_WEBKIT_LOGICAL_HEIGHT = 264;
  public static final int WEBKIT_MARGIN_AFTER_COLLAPSE = 265;
  public static final int WEBKIT_MARGIN_BEFORE_COLLAPSE = 266;
  public static final int WEBKIT_MARGIN_BOTTOM_COLLAPSE = 267;
  public static final int WEBKIT_MARGIN_TOP_COLLAPSE = 268;
  public static final int WEBKIT_MARGIN_COLLAPSE = 269;
  public static final int ALIAS_WEBKIT_MARGIN_AFTER = 270;
  public static final int ALIAS_WEBKIT_MARGIN_BEFORE = 271;
  public static final int ALIAS_WEBKIT_MARGIN_END = 272;
  public static final int ALIAS_WEBKIT_MARGIN_START = 273;
  public static final int WEBKIT_MASK = 280;
  public static final int WEBKIT_MASK_BOX_IMAGE = 281;
  public static final int WEBKIT_MASK_BOX_IMAGE_OUTSET = 282;
  public static final int WEBKIT_MASK_BOX_IMAGE_REPEAT = 283;
  public static final int WEBKIT_MASK_BOX_IMAGE_SLICE = 284;
  public static final int WEBKIT_MASK_BOX_IMAGE_SOURCE = 285;
  public static final int WEBKIT_MASK_BOX_IMAGE_WIDTH = 286;
  public static final int WEBKIT_MASK_CLIP = 287;
  public static final int WEBKIT_MASK_COMPOSITE = 288;
  public static final int WEBKIT_MASK_IMAGE = 289;
  public static final int WEBKIT_MASK_ORIGIN = 290;
  public static final int WEBKIT_MASK_POSITION = 291;
  public static final int WEBKIT_MASK_POSITION_X = 292;
  public static final int WEBKIT_MASK_POSITION_Y = 293;
  public static final int WEBKIT_MASK_REPEAT = 294;
  public static final int WEBKIT_MASK_SIZE = 297;
  public static final int ALIAS_WEBKIT_MAX_LOGICAL_WIDTH = 298;
  public static final int ALIAS_WEBKIT_MAX_LOGICAL_HEIGHT = 299;
  public static final int ALIAS_WEBKIT_MIN_LOGICAL_WIDTH = 300;
  public static final int ALIAS_WEBKIT_MIN_LOGICAL_HEIGHT = 301;
  public static final int ORDER = 303;
  public static final int ALIAS_WEBKIT_PADDING_AFTER = 304;
  public static final int ALIAS_WEBKIT_PADDING_BEFORE = 305;
  public static final int ALIAS_WEBKIT_PADDING_END = 306;
  public static final int ALIAS_WEBKIT_PADDING_START = 307;
  public static final int ALIAS_WEBKIT_PERSPECTIVE = 308;
  public static final int ALIAS_WEBKIT_PERSPECTIVE_ORIGIN = 309;
  public static final int WEBKIT_PERSPECTIVE_ORIGIN_X = 310;
  public static final int WEBKIT_PERSPECTIVE_ORIGIN_Y = 311;
  public static final int WEBKIT_PRINT_COLOR_ADJUST = 312;
  public static final int WEBKIT_RTL_ORDERING = 313;
  public static final int WEBKIT_RUBY_POSITION = 314;
  public static final int WEBKIT_TEXT_COMBINE = 315;
  public static final int WEBKIT_TEXT_DECORATIONS_IN_EFFECT = 316;
  public static final int ALIAS_WEBKIT_TEXT_EMPHASIS = 317;
  public static final int ALIAS_WEBKIT_TEXT_EMPHASIS_COLOR = 318;
  public static final int ALIAS_WEBKIT_TEXT_EMPHASIS_POSITION = 319;
  public static final int ALIAS_WEBKIT_TEXT_EMPHASIS_STYLE = 320;
  public static final int WEBKIT_TEXT_FILL_COLOR = 321;
  public static final int WEBKIT_TEXT_SECURITY = 322;
  public static final int WEBKIT_TEXT_STROKE = 323;
  public static final int WEBKIT_TEXT_STROKE_COLOR = 324;
  public static final int WEBKIT_TEXT_STROKE_WIDTH = 325;
  public static final int ALIAS_WEBKIT_TRANSFORM = 326;
  public static final int ALIAS_WEBKIT_TRANSFORM_ORIGIN = 327;
  public static final int WEBKIT_TRANSFORM_ORIGIN_X = 328;
  public static final int WEBKIT_TRANSFORM_ORIGIN_Y = 329;
  public static final int WEBKIT_TRANSFORM_ORIGIN_Z = 330;
  public static final int ALIAS_WEBKIT_TRANSFORM_STYLE = 331;
  public static final int ALIAS_WEBKIT_TRANSITION = 332;
  public static final int ALIAS_WEBKIT_TRANSITION_DELAY = 333;
  public static final int ALIAS_WEBKIT_TRANSITION_DURATION = 334;
  public static final int ALIAS_WEBKIT_TRANSITION_PROPERTY = 335;
  public static final int ALIAS_WEBKIT_TRANSITION_TIMING_FUNCTION = 336;
  public static final int WEBKIT_USER_DRAG = 337;
  public static final int WEBKIT_USER_MODIFY = 338;
  public static final int ALIAS_WEBKIT_USER_SELECT = 339;
  public static final int SHAPE_OUTSIDE = 347;
  public static final int SHAPE_MARGIN = 348;
  public static final int CLIP_PATH = 355;
  public static final int CLIP_RULE = 356;
  public static final int MASK = 357;
  public static final int FILTER = 359;
  public static final int FLOOD_COLOR = 360;
  public static final int FLOOD_OPACITY = 361;
  public static final int LIGHTING_COLOR = 362;
  public static final int STOP_COLOR = 363;
  public static final int STOP_OPACITY = 364;
  public static final int COLOR_INTERPOLATION = 365;
  public static final int COLOR_INTERPOLATION_FILTERS = 366;
  public static final int COLOR_RENDERING = 368;
  public static final int FILL = 369;
  public static final int FILL_OPACITY = 370;
  public static final int FILL_RULE = 371;
  public static final int MARKER = 372;
  public static final int MARKER_END = 373;
  public static final int MARKER_MID = 374;
  public static final int MARKER_START = 375;
  public static final int MASK_TYPE = 376;
  public static final int SHAPE_RENDERING = 377;
  public static final int STROKE = 378;
  public static final int STROKE_DASHARRAY = 379;
  public static final int STROKE_DASHOFFSET = 380;
  public static final int STROKE_LINECAP = 381;
  public static final int STROKE_LINEJOIN = 382;
  public static final int STROKE_MITERLIMIT = 383;
  public static final int STROKE_OPACITY = 384;
  public static final int STROKE_WIDTH = 385;
  public static final int ALIGNMENT_BASELINE = 386;
  public static final int BASELINE_SHIFT = 387;
  public static final int DOMINANT_BASELINE = 388;
  public static final int TEXT_ANCHOR = 392;
  public static final int VECTOR_EFFECT = 393;
  public static final int WRITING_MODE = 394;
  public static final int TEXT_DECORATION_LINE = 401;
  public static final int TEXT_DECORATION_STYLE = 402;
  public static final int TEXT_DECORATION_COLOR = 403;
  public static final int TEXT_ALIGN_LAST = 404;
  public static final int TEXT_UNDERLINE_POSITION = 405;
  public static final int MAX_ZOOM = 406;
  public static final int MIN_ZOOM = 407;
  public static final int ORIENTATION = 408;
  public static final int USER_ZOOM = 409;
  public static final int ALIAS_WEBKIT_APP_REGION = 412;
  public static final int ALIAS_WEBKIT_FILTER = 413;
  public static final int WEBKIT_BOX_DECORATION_BREAK = 414;
  public static final int WEBKIT_TAP_HIGHLIGHT_COLOR = 415;
  public static final int BUFFERED_RENDERING = 416;
  public static final int GRID_AUTO_ROWS = 417;
  public static final int GRID_AUTO_COLUMNS = 418;
  public static final int BACKGROUND_BLEND_MODE = 419;
  public static final int MIX_BLEND_MODE = 420;
  public static final int TOUCH_ACTION = 421;
  public static final int GRID_AREA = 422;
  public static final int GRID_TEMPLATE_AREAS = 423;
  public static final int ANIMATION = 424;
  public static final int ANIMATION_DELAY = 425;
  public static final int ANIMATION_DIRECTION = 426;
  public static final int ANIMATION_DURATION = 427;
  public static final int ANIMATION_FILL_MODE = 428;
  public static final int ANIMATION_ITERATION_COUNT = 429;
  public static final int ANIMATION_NAME = 430;
  public static final int ANIMATION_PLAY_STATE = 431;
  public static final int ANIMATION_TIMING_FUNCTION = 432;
  public static final int OBJECT_FIT = 433;
  public static final int PAINT_ORDER = 434;
  public static final int MASK_SOURCE_TYPE = 435;
  public static final int ISOLATION = 436;
  public static final int OBJECT_POSITION = 437;
  public static final int SHAPE_IMAGE_THRESHOLD = 439;
  public static final int COLUMN_FILL = 440;
  public static final int TEXT_JUSTIFY = 441;
  public static final int JUSTIFY_SELF = 443;
  public static final int SCROLL_BEHAVIOR = 444;
  public static final int WILL_CHANGE = 445;
  public static final int TRANSFORM = 446;
  public static final int TRANSFORM_ORIGIN = 447;
  public static final int TRANSFORM_STYLE = 448;
  public static final int PERSPECTIVE = 449;
  public static final int PERSPECTIVE_ORIGIN = 450;
  public static final int BACKFACE_VISIBILITY = 451;
  public static final int GRID_TEMPLATE = 452;
  public static final int GRID = 453;
  public static final int ALL = 454;
  public static final int JUSTIFY_ITEMS = 455;
  public static final int X = 461;
  public static final int Y = 462;
  public static final int RX = 463;
  public static final int RY = 464;
  public static final int FONT_SIZE_ADJUST = 465;
  public static final int CX = 466;
  public static final int CY = 467;
  public static final int R = 468;
  public static final int ALIAS_EPUB_CAPTION_SIDE = 469;
  public static final int ALIAS_EPUB_TEXT_COMBINE = 470;
  public static final int ALIAS_EPUB_TEXT_EMPHASIS = 471;
  public static final int ALIAS_EPUB_TEXT_EMPHASIS_COLOR = 472;
  public static final int ALIAS_EPUB_TEXT_EMPHASIS_STYLE = 473;
  public static final int ALIAS_EPUB_TEXT_ORIENTATION = 474;
  public static final int ALIAS_EPUB_TEXT_TRANSFORM = 475;
  public static final int ALIAS_EPUB_WORD_BREAK = 476;
  public static final int ALIAS_EPUB_WRITING_MODE = 477;
  public static final int ALIAS_WEBKIT_ALIGN_CONTENT = 478;
  public static final int ALIAS_WEBKIT_ALIGN_ITEMS = 479;
  public static final int ALIAS_WEBKIT_ALIGN_SELF = 480;
  public static final int ALIAS_WEBKIT_BORDER_BOTTOM_LEFT_RADIUS = 481;
  public static final int ALIAS_WEBKIT_BORDER_BOTTOM_RIGHT_RADIUS = 482;
  public static final int ALIAS_WEBKIT_BORDER_TOP_LEFT_RADIUS = 483;
  public static final int ALIAS_WEBKIT_BORDER_TOP_RIGHT_RADIUS = 484;
  public static final int ALIAS_WEBKIT_BOX_SIZING = 485;
  public static final int ALIAS_WEBKIT_FLEX = 486;
  public static final int ALIAS_WEBKIT_FLEX_BASIS = 487;
  public static final int ALIAS_WEBKIT_FLEX_DIRECTION = 488;
  public static final int ALIAS_WEBKIT_FLEX_FLOW = 489;
  public static final int ALIAS_WEBKIT_FLEX_GROW = 490;
  public static final int ALIAS_WEBKIT_FLEX_SHRINK = 491;
  public static final int ALIAS_WEBKIT_FLEX_WRAP = 492;
  public static final int ALIAS_WEBKIT_JUSTIFY_CONTENT = 493;
  public static final int ALIAS_WEBKIT_OPACITY = 494;
  public static final int ALIAS_WEBKIT_ORDER = 495;
  public static final int ALIAS_WEBKIT_SHAPE_IMAGE_THRESHOLD = 496;
  public static final int ALIAS_WEBKIT_SHAPE_MARGIN = 497;
  public static final int ALIAS_WEBKIT_SHAPE_OUTSIDE = 498;
  public static final int SCROLL_SNAP_TYPE = 499;
  public static final int TRANSLATE = 504;
  public static final int ROTATE = 505;
  public static final int SCALE = 506;
  public static final int IMAGE_ORIENTATION = 507;
  public static final int BACKDROP_FILTER = 508;
  public static final int TEXT_COMBINE_UPRIGHT = 509;
  public static final int TEXT_ORIENTATION = 510;
  public static final int GRID_COLUMN_GAP = 511;
  public static final int GRID_ROW_GAP = 512;
  public static final int GRID_GAP = 513;
  public static final int FONT_FEATURE_SETTINGS = 514;
  public static final int VARIABLE = 515;
  public static final int FONT_DISPLAY = 516;
  public static final int CONTAIN = 517;
  public static final int D = 518;
  public static final int BREAK_AFTER = 520;
  public static final int BREAK_BEFORE = 521;
  public static final int BREAK_INSIDE = 522;
  public static final int COLUMN_COUNT = 523;
  public static final int COLUMN_GAP = 524;
  public static final int COLUMN_RULE = 525;
  public static final int COLUMN_RULE_COLOR = 526;
  public static final int COLUMN_RULE_STYLE = 527;
  public static final int COLUMN_RULE_WIDTH = 528;
  public static final int COLUMN_SPAN = 529;
  public static final int COLUMN_WIDTH = 530;
  public static final int COLUMNS = 531;
  public static final int FONT_VARIANT_CAPS = 533;
  public static final int HYPHENS = 534;
  public static final int FONT_VARIANT_NUMERIC = 535;
  public static final int TEXT_SIZE_ADJUST = 536;
  public static final int ALIAS_WEBKIT_TEXT_SIZE_ADJUST = 537;
  public static final int OVERFLOW_ANCHOR = 538;
  public static final int USER_SELECT = 539;
  public static final int OFFSET_DISTANCE = 540;
  public static final int OFFSET_PATH = 541;
  public static final int OFFSET = 543;
  public static final int OFFSET_ANCHOR = 544;
  public static final int OFFSET_POSITION = 545;
  public static final int CARET_COLOR = 547;
  public static final int OFFSET_ROTATE = 548;
  public static final int FONT_VARIATION_SETTINGS = 549;
  public static final int INLINE_SIZE = 550;
  public static final int BLOCK_SIZE = 551;
  public static final int MIN_INLINE_SIZE = 552;
  public static final int MIN_BLOCK_SIZE = 553;
  public static final int MAX_INLINE_SIZE = 554;
  public static final int MAX_BLOCK_SIZE = 555;
  public static final int LINE_BREAK = 556;
  public static final int PLACE_CONTENT = 557;
  public static final int PLACE_ITEMS = 558;
  public static final int TRANSFORM_BOX = 559;
  public static final int PLACE_SELF = 560;
  public static final int SCROLL_SNAP_ALIGN = 561;
  public static final int SCROLL_PADDING = 562;
  public static final int SCROLL_PADDING_TOP = 563;
  public static final int SCROLL_PADDING_RIGHT = 564;
  public static final int SCROLL_PADDING_BOTTOM = 565;
  public static final int SCROLL_PADDING_LEFT = 566;
  public static final int SCROLL_PADDING_BLOCK = 567;
  public static final int SCROLL_PADDING_BLOCK_START = 568;
  public static final int SCROLL_PADDING_BLOCK_END = 569;
  public static final int SCROLL_PADDING_INLINE = 570;
  public static final int SCROLL_PADDING_INLINE_START = 571;
  public static final int SCROLL_PADDING_INLINE_END = 572;
  public static final int SCROLL_MARGIN = 573;
  public static final int SCROLL_MARGIN_TOP = 574;
  public static final int SCROLL_MARGIN_RIGHT = 575;
  public static final int SCROLL_MARGIN_BOTTOM = 576;
  public static final int SCROLL_MARGIN_LEFT = 577;
  public static final int SCROLL_MARGIN_BLOCK = 578;
  public static final int SCROLL_MARGIN_BLOCK_START = 579;
  public static final int SCROLL_MARGIN_BLOCK_END = 580;
  public static final int SCROLL_MARGIN_INLINE = 581;
  public static final int SCROLL_MARGIN_INLINE_START = 582;
  public static final int SCROLL_MARGIN_INLINE_END = 583;
  public static final int SCROLL_SNAP_STOP = 584;
  public static final int OVERSCROLL_BEHAVIOR = 585;
  public static final int OVERSCROLL_BEHAVIOR_X = 586;
  public static final int OVERSCROLL_BEHAVIOR_Y = 587;
  public static final int FONT_VARIANT_EAST_ASIAN = 588;
  public static final int TEXT_DECORATION_SKIP_INK = 589;
  public static final int SCROLL_CUSTOMIZATION = 590;
  public static final int ROW_GAP = 591;
  public static final int GAP = 592;
  public static final int VIEWPORT_FIT = 593;
  public static final int MARGIN_BLOCK_START = 594;
  public static final int MARGIN_BLOCK_END = 595;
  public static final int MARGIN_INLINE_START = 596;
  public static final int MARGIN_INLINE_END = 597;
  public static final int PADDING_BLOCK_START = 598;
  public static final int PADDING_BLOCK_END = 599;
  public static final int PADDING_INLINE_START = 600;
  public static final int PADDING_INLINE_END = 601;
  public static final int BORDER_BLOCK_END_COLOR = 602;
  public static final int BORDER_BLOCK_END_STYLE = 603;
  public static final int BORDER_BLOCK_END_WIDTH = 604;
  public static final int BORDER_BLOCK_START_COLOR = 605;
  public static final int BORDER_BLOCK_START_STYLE = 606;
  public static final int BORDER_BLOCK_START_WIDTH = 607;
  public static final int BORDER_INLINE_END_COLOR = 608;
  public static final int BORDER_INLINE_END_STYLE = 609;
  public static final int BORDER_INLINE_END_WIDTH = 610;
  public static final int BORDER_INLINE_START_COLOR = 611;
  public static final int BORDER_INLINE_START_STYLE = 612;
  public static final int BORDER_INLINE_START_WIDTH = 613;
  public static final int BORDER_BLOCK_START = 614;
  public static final int BORDER_BLOCK_END = 615;
  public static final int BORDER_INLINE_START = 616;
  public static final int BORDER_INLINE_END = 617;
  public static final int MARGIN_BLOCK = 618;
  public static final int MARGIN_INLINE = 619;
  public static final int PADDING_BLOCK = 620;
  public static final int PADDING_INLINE = 621;
  public static final int BORDER_BLOCK_COLOR = 622;
  public static final int BORDER_BLOCK_STYLE = 623;
  public static final int BORDER_BLOCK_WIDTH = 624;
  public static final int BORDER_INLINE_COLOR = 625;
  public static final int BORDER_INLINE_STYLE = 626;
  public static final int BORDER_INLINE_WIDTH = 627;
  public static final int BORDER_BLOCK = 628;
  public static final int BORDER_INLINE = 629;
  public static final int INSET_BLOCK_START = 630;
  public static final int INSET_BLOCK_END = 631;
  public static final int INSET_BLOCK = 632;
  public static final int INSET_INLINE_START = 633;
  public static final int INSET_INLINE_END = 634;
  public static final int INSET_INLINE = 635;
  public static final int INSET = 636;
  public static final int COLOR_SCHEME = 637;
  public static final int OVERFLOW_INLINE = 638;
  public static final int OVERFLOW_BLOCK = 639;
  public static final int FORCED_COLOR_ADJUST = 640;
  public static final int INHERITS = 641;
  public static final int INITIAL_VALUE = 642;
  public static final int SYNTAX = 643;
  public static final int OVERSCROLL_BEHAVIOR_INLINE = 644;
  public static final int OVERSCROLL_BEHAVIOR_BLOCK = 645;
  public static final int FONT_OPTICAL_SIZING = 647;
  public static final int CONTAIN_INTRINSIC_BLOCK_SIZE = 648;
  public static final int CONTAIN_INTRINSIC_HEIGHT = 649;
  public static final int CONTAIN_INTRINSIC_INLINE_SIZE = 650;
  public static final int CONTAIN_INTRINSIC_SIZE = 651;
  public static final int CONTAIN_INTRINSIC_WIDTH = 652;
  public static final int ORIGIN_TRIAL_TEST_PROPERTY = 654;
  public static final int MATH_STYLE = 656;
  public static final int ASPECT_RATIO = 657;
  public static final int APPEARANCE = 658;
  public static final int RUBY_POSITION = 660;
  public static final int TEXT_UNDERLINE_OFFSET = 661;
  public static final int CONTENT_VISIBILITY = 662;
  public static final int TEXT_DECORATION_THICKNESS = 663;
  public static final int PAGE_ORIENTATION = 664;
  public static final int ANIMATION_TIMELINE = 665;
  public static final int COUNTER_SET = 666;
  public static final int SOURCE = 667;
  public static final int START = 668;
  public static final int END = 669;
  public static final int TIME_RANGE = 670;
  public static final int SCROLLBAR_GUTTER = 671;
  public static final int ASCENT_OVERRIDE = 672;
  public static final int DESCENT_OVERRIDE = 673;
  public static final int ADVANCE_OVERRIDE = 674;
  public static final int LINE_GAP_OVERRIDE = 675;
  public static final int MATH_SHIFT = 676;
  public static final int MATH_DEPTH = 677;
  public static final int OVERFLOW_CLIP_MARGIN = 679;
  public static final int SCROLLBAR_WIDTH = 680;
  public static final int SYSTEM = 681;
  public static final int NEGATIVE = 682;
  public static final int PREFIX = 683;
  public static final int SUFFIX = 684;
  public static final int RANGE = 685;
  public static final int PAD = 686;
  public static final int FALLBACK = 687;
  public static final int SYMBOLS = 688;
  public static final int ADDITIVE_SYMBOLS = 689;
  public static final int SPEAK_AS = 690;
  public static final int BORDER_START_START_RADIUS = 691;
  public static final int BORDER_START_END_RADIUS = 692;
  public static final int BORDER_END_START_RADIUS = 693;
  public static final int BORDER_END_END_RADIUS = 694;
  public static final int ACCENT_COLOR = 695;
  public static final int SIZE_ADJUST = 696;
  public static final int CONTAINER_NAME = 697;
  public static final int CONTAINER_TYPE = 698;
  public static final int CONTAINER = 699;
  public static final int FONT_SYNTHESIS_WEIGHT = 700;
  public static final int FONT_SYNTHESIS_STYLE = 701;
  public static final int APP_REGION = 702;
  public static final int FONT_SYNTHESIS_SMALL_CAPS = 703;
  public static final int FONT_SYNTHESIS = 704;
  public static final int TEXT_EMPHASIS = 705;
  public static final int TEXT_EMPHASIS_COLOR = 706;
  public static final int TEXT_EMPHASIS_POSITION = 707;
  public static final int TEXT_EMPHASIS_STYLE = 708;
  public static final int FONT_PALETTE = 709;
  public static final int BASE_PALETTE = 710;
  public static final int OVERRIDE_COLORS = 711;
  public static final int VIEW_TRANSITION_NAME = 712;
  public static final int OBJECT_VIEW_BOX = 713;
  public static final int OBJECT_OVERFLOW = 714;
  public static final int ANCHOR_NAME = 719;
  public static final int POSITION_FALLBACK = 720;
  public static final int POPOVER_SHOW_DELAY = 722;
  public static final int POPOVER_HIDE_DELAY = 723;
  public static final int HYPHENATE_CHARACTER = 724;
  public static final int SCROLL_TIMELINE = 725;
  public static final int SCROLL_TIMELINE_NAME = 726;
  public static final int SCROLL_TIMELINE_AXIS = 727;
  public static final int VIEW_TIMELINE = 728;
  public static final int VIEW_TIMELINE_AXIS = 729;
  public static final int VIEW_TIMELINE_INSET = 730;
  public static final int VIEW_TIMELINE_NAME = 731;
  public static final int INITIAL_LETTER = 733;
  public static final int HYPHENATE_LIMIT_CHARS = 734;
  public static final int ANIMATION_DELAY_START = 735;
  public static final int ANIMATION_DELAY_END = 736;
  public static final int FONT_VARIANT_POSITION = 737;
  public static final int FONT_VARIANT_ALTERNATES = 738;
  public static final int BASELINE_SOURCE = 739;
  public static final int ANIMATION_RANGE = 740;
  public static final int ANIMATION_RANGE_START = 741;
  public static final int ANIMATION_RANGE_END = 742;
  public static final int ANIMATION_COMPOSITION = 743;
  public static final int TOP_LAYER = 744;
  public static final int ANCHOR_DEFAULT = 745;
  public static final int TEXT_WRAP = 746;
  public static final int TEXT_BOX_TRIM = 747;
  public static final int OVERLAY = 748;
  public static final int WHITE_SPACE_COLLAPSE = 749;
  public static final int SCROLL_TIMELINE_ATTACHMENT = 750;
  public static final int VIEW_TIMELINE_ATTACHMENT = 751;
  public static final int SCROLL_START_BLOCK = 752;
  public static final int SCROLL_START_INLINE = 753;
  public static final int SCROLL_START_X = 754;
  public static final int SCROLL_START_Y = 755;
  public static final int SCROLL_START = 756;
  public static final int SCROLL_START_TARGET_BLOCK = 757;
  public static final int SCROLL_START_TARGET_INLINE = 758;
  public static final int SCROLL_START_TARGET_X = 759;
  public static final int SCROLL_START_TARGET_Y = 760;
  public static final int SCROLL_START_TARGET = 761;
  public static final int TIMELINE_SCOPE = 762;
  public static final int SCROLLBAR_COLOR = 763;
  public static final int POSITION_FALLBACK_BOUNDS = 765;
  public static final int TRANSITION_BEHAVIOR = 766;
  public static final int TEXT_AUTOSPACE = 767;
  public static final int NAVIGATION = 768;
  public static final int DYNAMIC_RANGE_LIMIT = 769;
  public static final int FIELD_SIZING = 770;
  public static final int TEXT_SPACING_TRIM = 771;
  public static final int MASK_IMAGE = 772;
  public static final int MASK_CLIP = 773;
  public static final int MASK_SIZE = 774;
  public static final int MASK_ORIGIN = 775;
  public static final int TEXT_SPACING = 776;
  public static final int MASK_REPEAT = 777;
  public static final int MASK_COMPOSITE = 778;
  public static final int MASK_POSITION = 779;
  public static final int MASK_MODE = 780;
  public static final int INSET_AREA = 781;
  public static final int VIEW_TRANSITION_CLASS = 782;
  public static final int POSITION_TRY_ORDER = 783;
  public static final int POSITION_TRY_OPTIONS = 784;
  public static final int POSITION_TRY = 785;
  public static final int MIN_VALUE = 0;
  public static final int MAX_VALUE = 785;

  public static boolean isKnownValue(int value) {
    switch (value) {
      case 0:
      case 1:
      case 2:
      case 3:
      case 4:
      case 5:
      case 6:
      case 7:
      case 8:
      case 9:
      case 10:
      case 11:
      case 12:
      case 13:
      case 14:
      case 15:
      case 16:
      case 17:
      case 18:
      case 19:
      case 20:
      case 21:
      case 22:
      case 23:
      case 24:
      case 25:
      case 26:
      case 27:
      case 28:
      case 29:
      case 30:
      case 33:
      case 34:
      case 35:
      case 36:
      case 37:
      case 38:
      case 39:
      case 40:
      case 41:
      case 42:
      case 43:
      case 44:
      case 45:
      case 46:
      case 47:
      case 48:
      case 49:
      case 50:
      case 51:
      case 52:
      case 53:
      case 54:
      case 55:
      case 56:
      case 57:
      case 58:
      case 59:
      case 60:
      case 61:
      case 62:
      case 63:
      case 64:
      case 65:
      case 66:
      case 67:
      case 68:
      case 69:
      case 70:
      case 71:
      case 72:
      case 73:
      case 74:
      case 75:
      case 76:
      case 77:
      case 78:
      case 79:
      case 80:
      case 81:
      case 82:
      case 83:
      case 84:
      case 85:
      case 86:
      case 87:
      case 88:
      case 89:
      case 90:
      case 91:
      case 92:
      case 93:
      case 94:
      case 95:
      case 96:
      case 97:
      case 98:
      case 99:
      case 100:
      case 101:
      case 102:
      case 103:
      case 104:
      case 105:
      case 106:
      case 107:
      case 108:
      case 109:
      case 110:
      case 111:
      case 112:
      case 113:
      case 114:
      case 115:
      case 116:
      case 117:
      case 118:
      case 119:
      case 120:
      case 121:
      case 122:
      case 123:
      case 124:
      case 125:
      case 126:
      case 127:
      case 128:
      case 129:
      case 130:
      case 136:
      case 142:
      case 143:
      case 149:
      case 150:
      case 151:
      case 152:
      case 153:
      case 154:
      case 155:
      case 156:
      case 157:
      case 158:
      case 159:
      case 160:
      case 161:
      case 162:
      case 163:
      case 164:
      case 165:
      case 166:
      case 167:
      case 168:
      case 169:
      case 170:
      case 171:
      case 172:
      case 173:
      case 174:
      case 175:
      case 177:
      case 178:
      case 180:
      case 181:
      case 182:
      case 183:
      case 184:
      case 185:
      case 186:
      case 187:
      case 188:
      case 189:
      case 190:
      case 191:
      case 192:
      case 193:
      case 195:
      case 196:
      case 197:
      case 198:
      case 199:
      case 200:
      case 201:
      case 202:
      case 203:
      case 204:
      case 205:
      case 208:
      case 209:
      case 210:
      case 211:
      case 212:
      case 215:
      case 216:
      case 217:
      case 218:
      case 219:
      case 221:
      case 222:
      case 223:
      case 224:
      case 225:
      case 226:
      case 227:
      case 230:
      case 231:
      case 232:
      case 233:
      case 234:
      case 235:
      case 236:
      case 237:
      case 238:
      case 239:
      case 240:
      case 242:
      case 243:
      case 244:
      case 245:
      case 246:
      case 247:
      case 248:
      case 249:
      case 250:
      case 252:
      case 259:
      case 260:
      case 263:
      case 264:
      case 265:
      case 266:
      case 267:
      case 268:
      case 269:
      case 270:
      case 271:
      case 272:
      case 273:
      case 280:
      case 281:
      case 282:
      case 283:
      case 284:
      case 285:
      case 286:
      case 287:
      case 288:
      case 289:
      case 290:
      case 291:
      case 292:
      case 293:
      case 294:
      case 297:
      case 298:
      case 299:
      case 300:
      case 301:
      case 303:
      case 304:
      case 305:
      case 306:
      case 307:
      case 308:
      case 309:
      case 310:
      case 311:
      case 312:
      case 313:
      case 314:
      case 315:
      case 316:
      case 317:
      case 318:
      case 319:
      case 320:
      case 321:
      case 322:
      case 323:
      case 324:
      case 325:
      case 326:
      case 327:
      case 328:
      case 329:
      case 330:
      case 331:
      case 332:
      case 333:
      case 334:
      case 335:
      case 336:
      case 337:
      case 338:
      case 339:
      case 347:
      case 348:
      case 355:
      case 356:
      case 357:
      case 359:
      case 360:
      case 361:
      case 362:
      case 363:
      case 364:
      case 365:
      case 366:
      case 368:
      case 369:
      case 370:
      case 371:
      case 372:
      case 373:
      case 374:
      case 375:
      case 376:
      case 377:
      case 378:
      case 379:
      case 380:
      case 381:
      case 382:
      case 383:
      case 384:
      case 385:
      case 386:
      case 387:
      case 388:
      case 392:
      case 393:
      case 394:
      case 401:
      case 402:
      case 403:
      case 404:
      case 405:
      case 406:
      case 407:
      case 408:
      case 409:
      case 412:
      case 413:
      case 414:
      case 415:
      case 416:
      case 417:
      case 418:
      case 419:
      case 420:
      case 421:
      case 422:
      case 423:
      case 424:
      case 425:
      case 426:
      case 427:
      case 428:
      case 429:
      case 430:
      case 431:
      case 432:
      case 433:
      case 434:
      case 435:
      case 436:
      case 437:
      case 439:
      case 440:
      case 441:
      case 443:
      case 444:
      case 445:
      case 446:
      case 447:
      case 448:
      case 449:
      case 450:
      case 451:
      case 452:
      case 453:
      case 454:
      case 455:
      case 461:
      case 462:
      case 463:
      case 464:
      case 465:
      case 466:
      case 467:
      case 468:
      case 469:
      case 470:
      case 471:
      case 472:
      case 473:
      case 474:
      case 475:
      case 476:
      case 477:
      case 478:
      case 479:
      case 480:
      case 481:
      case 482:
      case 483:
      case 484:
      case 485:
      case 486:
      case 487:
      case 488:
      case 489:
      case 490:
      case 491:
      case 492:
      case 493:
      case 494:
      case 495:
      case 496:
      case 497:
      case 498:
      case 499:
      case 504:
      case 505:
      case 506:
      case 507:
      case 508:
      case 509:
      case 510:
      case 511:
      case 512:
      case 513:
      case 514:
      case 515:
      case 516:
      case 517:
      case 518:
      case 520:
      case 521:
      case 522:
      case 523:
      case 524:
      case 525:
      case 526:
      case 527:
      case 528:
      case 529:
      case 530:
      case 531:
      case 533:
      case 534:
      case 535:
      case 536:
      case 537:
      case 538:
      case 539:
      case 540:
      case 541:
      case 543:
      case 544:
      case 545:
      case 547:
      case 548:
      case 549:
      case 550:
      case 551:
      case 552:
      case 553:
      case 554:
      case 555:
      case 556:
      case 557:
      case 558:
      case 559:
      case 560:
      case 561:
      case 562:
      case 563:
      case 564:
      case 565:
      case 566:
      case 567:
      case 568:
      case 569:
      case 570:
      case 571:
      case 572:
      case 573:
      case 574:
      case 575:
      case 576:
      case 577:
      case 578:
      case 579:
      case 580:
      case 581:
      case 582:
      case 583:
      case 584:
      case 585:
      case 586:
      case 587:
      case 588:
      case 589:
      case 590:
      case 591:
      case 592:
      case 593:
      case 594:
      case 595:
      case 596:
      case 597:
      case 598:
      case 599:
      case 600:
      case 601:
      case 602:
      case 603:
      case 604:
      case 605:
      case 606:
      case 607:
      case 608:
      case 609:
      case 610:
      case 611:
      case 612:
      case 613:
      case 614:
      case 615:
      case 616:
      case 617:
      case 618:
      case 619:
      case 620:
      case 621:
      case 622:
      case 623:
      case 624:
      case 625:
      case 626:
      case 627:
      case 628:
      case 629:
      case 630:
      case 631:
      case 632:
      case 633:
      case 634:
      case 635:
      case 636:
      case 637:
      case 638:
      case 639:
      case 640:
      case 641:
      case 642:
      case 643:
      case 644:
      case 645:
      case 647:
      case 648:
      case 649:
      case 650:
      case 651:
      case 652:
      case 654:
      case 656:
      case 657:
      case 658:
      case 660:
      case 661:
      case 662:
      case 663:
      case 664:
      case 665:
      case 666:
      case 667:
      case 668:
      case 669:
      case 670:
      case 671:
      case 672:
      case 673:
      case 674:
      case 675:
      case 676:
      case 677:
      case 679:
      case 680:
      case 681:
      case 682:
      case 683:
      case 684:
      case 685:
      case 686:
      case 687:
      case 688:
      case 689:
      case 690:
      case 691:
      case 692:
      case 693:
      case 694:
      case 695:
      case 696:
      case 697:
      case 698:
      case 699:
      case 700:
      case 701:
      case 702:
      case 703:
      case 704:
      case 705:
      case 706:
      case 707:
      case 708:
      case 709:
      case 710:
      case 711:
      case 712:
      case 713:
      case 714:
      case 719:
      case 720:
      case 722:
      case 723:
      case 724:
      case 725:
      case 726:
      case 727:
      case 728:
      case 729:
      case 730:
      case 731:
      case 733:
      case 734:
      case 735:
      case 736:
      case 737:
      case 738:
      case 739:
      case 740:
      case 741:
      case 742:
      case 743:
      case 744:
      case 745:
      case 746:
      case 747:
      case 748:
      case 749:
      case 750:
      case 751:
      case 752:
      case 753:
      case 754:
      case 755:
      case 756:
      case 757:
      case 758:
      case 759:
      case 760:
      case 761:
      case 762:
      case 763:
      case 765:
      case 766:
      case 767:
      case 768:
      case 769:
      case 770:
      case 771:
      case 772:
      case 773:
      case 774:
      case 775:
      case 776:
      case 777:
      case 778:
      case 779:
      case 780:
      case 781:
      case 782:
      case 783:
      case 784:
      case 785:
        return true;
    }
    return false;
  }

  public static void validate(int value) {
    if (IS_EXTENSIBLE || isKnownValue(value)) return;
    throw new org.chromium.mojo.bindings.DeserializationException("Invalid enum value.");
  }

  public static int toKnownValue(int value) {
    return value;
  }

  private CssSampleId() {}
}
